import { z } from 'zod';
import { GeoCoordinatesDTOSchema } from '../common/geo.dto.js';
import { BuildingUsageTypeSchema, HvacTypeSchema, MainFuelTypeSchema, OperationalStatusSchema } from '../common/graphql-setup-enums.js';
/** Calidad térmica de envolvente */
export declare const BuildingInsulationQualitySchema: z.ZodEnum<["POOR", "AVERAGE", "HIGH"]>;
/** Tipo de cubierta */
export declare const BuildingRoofTypeSchema: z.ZodEnum<["GREEN", "REFLECTIVE", "STANDARD"]>;
/** Estado técnico de mantenimiento / performance */
export declare const BuildingMaintenanceStatusSchema: z.ZodEnum<["OPTIMAL", "DEGRADED", "CRITICAL"]>;
/** Tecnología de iluminación dominante */
export declare const BuildingLightingTechnologySchema: z.ZodEnum<["LED", "FLUORESCENT", "HID", "MIXED"]>;
/** Granularidad datos energía */
export declare const BuildingDataGranularitySchema: z.ZodEnum<["MANUAL", "MONTHLY", "DAILY", "TELEMETRY"]>;
/** Topología submedición */
export declare const BuildingSubmeteringTopologySchema: z.ZodEnum<["CENTRALIZED", "BY_FLOOR", "BY_LOAD", "NONE"]>;
export type BuildingInsulationQuality = z.infer<typeof BuildingInsulationQualitySchema>;
export type BuildingRoofType = z.infer<typeof BuildingRoofTypeSchema>;
export type BuildingMaintenanceStatus = z.infer<typeof BuildingMaintenanceStatusSchema>;
export type BuildingLightingTechnology = z.infer<typeof BuildingLightingTechnologySchema>;
export type BuildingDataGranularity = z.infer<typeof BuildingDataGranularitySchema>;
export type BuildingSubmeteringTopology = z.infer<typeof BuildingSubmeteringTopologySchema>;
export declare const BuildingDTOSchema: z.ZodObject<{
    id: z.ZodUnion<[z.ZodString, z.ZodString]>;
    organizationId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    regionId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    branchId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    name: z.ZodString;
    status: z.ZodEnum<["OPERATIONAL", "INACTIVE", "MAINTENANCE", "STANDBY"]>;
    usageTypeEnum: z.ZodEnum<["STORAGE_INDUSTRIAL"]>;
    m2Surface: z.ZodNumber;
    m3Volume: z.ZodNumber;
    footprintM2: z.ZodOptional<z.ZodNumber>;
    floorsCount: z.ZodDefault<z.ZodNumber>;
    yearBuilt: z.ZodNumber;
    renovationYear: z.ZodOptional<z.ZodNumber>;
    insulationQuality: z.ZodDefault<z.ZodEnum<["POOR", "AVERAGE", "HIGH"]>>;
    windowWallRatio: z.ZodDefault<z.ZodNumber>;
    roofType: z.ZodDefault<z.ZodEnum<["GREEN", "REFLECTIVE", "STANDARD"]>>;
    coordinates: z.ZodObject<{
        lat: z.ZodNumber;
        lng: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        lat: number;
        lng: number;
    }, {
        lat: number;
        lng: number;
    }>;
    hvacType: z.ZodEnum<["CENTRAL_CHILLER"]>;
    hvacAgeYears: z.ZodOptional<z.ZodNumber>;
    hvacEfficiencyRating: z.ZodOptional<z.ZodNumber>;
    maintenanceStatus: z.ZodDefault<z.ZodEnum<["OPTIMAL", "DEGRADED", "CRITICAL"]>>;
    lastEnergyAuditDate: z.ZodOptional<z.ZodString>;
    mainFuelType: z.ZodEnum<["ELECTRICITY", "GAS", "DIESEL", "RENEWABLE"]>;
    lightingTechnology: z.ZodDefault<z.ZodEnum<["LED", "FLUORESCENT", "HID", "MIXED"]>>;
    lightingPowerDensity: z.ZodOptional<z.ZodNumber>;
    hasBms: z.ZodBoolean;
    bmsVendor: z.ZodOptional<z.ZodString>;
    bmsProtocols: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    hasSmartMetering: z.ZodBoolean;
    dataGranularity: z.ZodDefault<z.ZodEnum<["MANUAL", "MONTHLY", "DAILY", "TELEMETRY"]>>;
    submeteringTopology: z.ZodDefault<z.ZodEnum<["CENTRALIZED", "BY_FLOOR", "BY_LOAD", "NONE"]>>;
    buildingCertifications: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    epcRating: z.ZodOptional<z.ZodString>;
    onsiteGenerationCapacityKw: z.ZodOptional<z.ZodNumber>;
    airQualitySensors: z.ZodDefault<z.ZodBoolean>;
    waterRecyclingSystem: z.ZodDefault<z.ZodBoolean>;
    evChargingPoints: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
    /** Compat texto libre (no aparece en el constructor Enterprise nominal). */
    usageType: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "OPERATIONAL" | "INACTIVE" | "MAINTENANCE" | "STANDBY";
    name: string;
    id: string;
    organizationId: string;
    coordinates: {
        lat: number;
        lng: number;
    };
    regionId: string;
    branchId: string;
    usageTypeEnum: "STORAGE_INDUSTRIAL";
    m2Surface: number;
    m3Volume: number;
    floorsCount: number;
    yearBuilt: number;
    insulationQuality: "POOR" | "AVERAGE" | "HIGH";
    windowWallRatio: number;
    roofType: "GREEN" | "REFLECTIVE" | "STANDARD";
    hvacType: "CENTRAL_CHILLER";
    maintenanceStatus: "OPTIMAL" | "DEGRADED" | "CRITICAL";
    mainFuelType: "ELECTRICITY" | "GAS" | "DIESEL" | "RENEWABLE";
    lightingTechnology: "LED" | "FLUORESCENT" | "HID" | "MIXED";
    hasBms: boolean;
    bmsProtocols: string[];
    hasSmartMetering: boolean;
    dataGranularity: "MANUAL" | "MONTHLY" | "DAILY" | "TELEMETRY";
    submeteringTopology: "NONE" | "CENTRALIZED" | "BY_FLOOR" | "BY_LOAD";
    buildingCertifications: string[];
    airQualitySensors: boolean;
    waterRecyclingSystem: boolean;
    evChargingPoints: number;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    renovationYear?: number | undefined;
    footprintM2?: number | undefined;
    hvacAgeYears?: number | undefined;
    hvacEfficiencyRating?: number | undefined;
    lastEnergyAuditDate?: string | undefined;
    lightingPowerDensity?: number | undefined;
    bmsVendor?: string | undefined;
    epcRating?: string | undefined;
    onsiteGenerationCapacityKw?: number | undefined;
    usageType?: string | undefined;
}, {
    status: "OPERATIONAL" | "INACTIVE" | "MAINTENANCE" | "STANDBY";
    name: string;
    id: string;
    organizationId: string;
    coordinates: {
        lat: number;
        lng: number;
    };
    regionId: string;
    branchId: string;
    usageTypeEnum: "STORAGE_INDUSTRIAL";
    m2Surface: number;
    m3Volume: number;
    yearBuilt: number;
    hvacType: "CENTRAL_CHILLER";
    mainFuelType: "ELECTRICITY" | "GAS" | "DIESEL" | "RENEWABLE";
    hasBms: boolean;
    hasSmartMetering: boolean;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    renovationYear?: number | undefined;
    footprintM2?: number | undefined;
    floorsCount?: number | undefined;
    insulationQuality?: "POOR" | "AVERAGE" | "HIGH" | undefined;
    windowWallRatio?: number | undefined;
    roofType?: "GREEN" | "REFLECTIVE" | "STANDARD" | undefined;
    hvacAgeYears?: number | undefined;
    hvacEfficiencyRating?: number | undefined;
    maintenanceStatus?: "OPTIMAL" | "DEGRADED" | "CRITICAL" | undefined;
    lastEnergyAuditDate?: string | undefined;
    lightingTechnology?: "LED" | "FLUORESCENT" | "HID" | "MIXED" | undefined;
    lightingPowerDensity?: number | undefined;
    bmsVendor?: string | undefined;
    bmsProtocols?: string[] | undefined;
    dataGranularity?: "MANUAL" | "MONTHLY" | "DAILY" | "TELEMETRY" | undefined;
    submeteringTopology?: "NONE" | "CENTRALIZED" | "BY_FLOOR" | "BY_LOAD" | undefined;
    buildingCertifications?: string[] | undefined;
    epcRating?: string | undefined;
    onsiteGenerationCapacityKw?: number | undefined;
    airQualitySensors?: boolean | undefined;
    waterRecyclingSystem?: boolean | undefined;
    evChargingPoints?: number | undefined;
    usageType?: string | undefined;
}>;
export declare class BuildingDTO {
    readonly id: string;
    readonly organizationId: string;
    readonly regionId: string;
    readonly branchId: string;
    readonly name: string;
    readonly status: z.infer<typeof OperationalStatusSchema>;
    readonly usageTypeEnum: z.infer<typeof BuildingUsageTypeSchema>;
    readonly m2Surface: number;
    readonly m3Volume: number;
    readonly footprintM2?: number;
    readonly floorsCount: number;
    readonly yearBuilt: number;
    readonly renovationYear?: number;
    readonly insulationQuality: z.infer<typeof BuildingInsulationQualitySchema>;
    readonly windowWallRatio: number;
    readonly roofType: z.infer<typeof BuildingRoofTypeSchema>;
    readonly coordinates: z.infer<typeof GeoCoordinatesDTOSchema>;
    readonly hvacType: z.infer<typeof HvacTypeSchema>;
    readonly hvacAgeYears?: number;
    readonly hvacEfficiencyRating?: number;
    readonly maintenanceStatus: z.infer<typeof BuildingMaintenanceStatusSchema>;
    readonly lastEnergyAuditDate?: string;
    readonly mainFuelType: z.infer<typeof MainFuelTypeSchema>;
    readonly lightingTechnology: z.infer<typeof BuildingLightingTechnologySchema>;
    readonly lightingPowerDensity?: number;
    readonly hasBms: boolean;
    readonly bmsVendor?: string;
    readonly bmsProtocols: string[];
    readonly hasSmartMetering: boolean;
    readonly dataGranularity: z.infer<typeof BuildingDataGranularitySchema>;
    readonly submeteringTopology: z.infer<typeof BuildingSubmeteringTopologySchema>;
    readonly buildingCertifications: string[];
    readonly epcRating?: string;
    readonly onsiteGenerationCapacityKw?: number;
    readonly airQualitySensors: boolean;
    readonly waterRecyclingSystem: boolean;
    readonly evChargingPoints: number;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    /** Legacy compat */
    readonly usageType?: string;
    constructor(id: string, organizationId: string, regionId: string, branchId: string, name: string, status: z.infer<typeof OperationalStatusSchema>, usageTypeEnum: z.infer<typeof BuildingUsageTypeSchema>, m2Surface: number, m3Volume: number, footprintM2: number | null | undefined, floorsCount: number | null | undefined, yearBuilt: number, renovationYear: number | null | undefined, insulationQuality: z.infer<typeof BuildingInsulationQualitySchema> | null | undefined, windowWallRatio: number | null | undefined, roofType: z.infer<typeof BuildingRoofTypeSchema> | null | undefined, coordinates: z.infer<typeof GeoCoordinatesDTOSchema>, hvacType: z.infer<typeof HvacTypeSchema>, hvacAgeYears: number | null | undefined, hvacEfficiencyRating: number | null | undefined, maintenanceStatus: z.infer<typeof BuildingMaintenanceStatusSchema> | null | undefined, lastEnergyAuditDate: string | null | undefined, mainFuelType: z.infer<typeof MainFuelTypeSchema>, lightingTechnology: z.infer<typeof BuildingLightingTechnologySchema> | null | undefined, lightingPowerDensity: number | null | undefined, hasBms: boolean, bmsVendor: string | null | undefined, bmsProtocols: string[] | null | undefined, hasSmartMetering: boolean, dataGranularity: BuildingDataGranularity | null | undefined, submeteringTopology: BuildingSubmeteringTopology | null | undefined, buildingCertifications: string[] | null | undefined, epcRating: string | null | undefined, onsiteGenerationCapacityKw: number | null | undefined, airQualitySensors: boolean | null | undefined, waterRecyclingSystem: boolean | null | undefined, evChargingPoints: number | null | undefined, createdAt?: string, updatedAt?: string, usageType?: string);
}
export type BuildingDTOInput = z.infer<typeof BuildingDTOSchema>;
export declare const parseBuildingDTO: (input: unknown) => BuildingDTO;
export declare const safeParseBuildingDTO: (input: unknown) => z.SafeParseReturnType<{
    status: "OPERATIONAL" | "INACTIVE" | "MAINTENANCE" | "STANDBY";
    name: string;
    id: string;
    organizationId: string;
    coordinates: {
        lat: number;
        lng: number;
    };
    regionId: string;
    branchId: string;
    usageTypeEnum: "STORAGE_INDUSTRIAL";
    m2Surface: number;
    m3Volume: number;
    yearBuilt: number;
    hvacType: "CENTRAL_CHILLER";
    mainFuelType: "ELECTRICITY" | "GAS" | "DIESEL" | "RENEWABLE";
    hasBms: boolean;
    hasSmartMetering: boolean;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    renovationYear?: number | undefined;
    footprintM2?: number | undefined;
    floorsCount?: number | undefined;
    insulationQuality?: "POOR" | "AVERAGE" | "HIGH" | undefined;
    windowWallRatio?: number | undefined;
    roofType?: "GREEN" | "REFLECTIVE" | "STANDARD" | undefined;
    hvacAgeYears?: number | undefined;
    hvacEfficiencyRating?: number | undefined;
    maintenanceStatus?: "OPTIMAL" | "DEGRADED" | "CRITICAL" | undefined;
    lastEnergyAuditDate?: string | undefined;
    lightingTechnology?: "LED" | "FLUORESCENT" | "HID" | "MIXED" | undefined;
    lightingPowerDensity?: number | undefined;
    bmsVendor?: string | undefined;
    bmsProtocols?: string[] | undefined;
    dataGranularity?: "MANUAL" | "MONTHLY" | "DAILY" | "TELEMETRY" | undefined;
    submeteringTopology?: "NONE" | "CENTRALIZED" | "BY_FLOOR" | "BY_LOAD" | undefined;
    buildingCertifications?: string[] | undefined;
    epcRating?: string | undefined;
    onsiteGenerationCapacityKw?: number | undefined;
    airQualitySensors?: boolean | undefined;
    waterRecyclingSystem?: boolean | undefined;
    evChargingPoints?: number | undefined;
    usageType?: string | undefined;
}, {
    status: "OPERATIONAL" | "INACTIVE" | "MAINTENANCE" | "STANDBY";
    name: string;
    id: string;
    organizationId: string;
    coordinates: {
        lat: number;
        lng: number;
    };
    regionId: string;
    branchId: string;
    usageTypeEnum: "STORAGE_INDUSTRIAL";
    m2Surface: number;
    m3Volume: number;
    floorsCount: number;
    yearBuilt: number;
    insulationQuality: "POOR" | "AVERAGE" | "HIGH";
    windowWallRatio: number;
    roofType: "GREEN" | "REFLECTIVE" | "STANDARD";
    hvacType: "CENTRAL_CHILLER";
    maintenanceStatus: "OPTIMAL" | "DEGRADED" | "CRITICAL";
    mainFuelType: "ELECTRICITY" | "GAS" | "DIESEL" | "RENEWABLE";
    lightingTechnology: "LED" | "FLUORESCENT" | "HID" | "MIXED";
    hasBms: boolean;
    bmsProtocols: string[];
    hasSmartMetering: boolean;
    dataGranularity: "MANUAL" | "MONTHLY" | "DAILY" | "TELEMETRY";
    submeteringTopology: "NONE" | "CENTRALIZED" | "BY_FLOOR" | "BY_LOAD";
    buildingCertifications: string[];
    airQualitySensors: boolean;
    waterRecyclingSystem: boolean;
    evChargingPoints: number;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    renovationYear?: number | undefined;
    footprintM2?: number | undefined;
    hvacAgeYears?: number | undefined;
    hvacEfficiencyRating?: number | undefined;
    lastEnergyAuditDate?: string | undefined;
    lightingPowerDensity?: number | undefined;
    bmsVendor?: string | undefined;
    epcRating?: string | undefined;
    onsiteGenerationCapacityKw?: number | undefined;
    usageType?: string | undefined;
}>;
//# sourceMappingURL=building.dto.d.ts.map