import { z } from 'zod';
import { AssetTypeSchema } from '../common/domain-enums.js';
import { AssetLifecycleStatusSchema } from '../common/graphql-setup-enums.js';
export declare const AssetCriticalitySchema: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "MISSION_CRITICAL"]>;
export declare const AssetEnergySourceSchema: z.ZodEnum<["ELECTRICITY", "NATURAL_GAS", "DIESEL", "BIOMASS", "STEAM", "HYDROGEN"]>;
export declare const AssetGhgScopeSchema: z.ZodEnum<["SCOPE_1", "SCOPE_2", "SCOPE_3"]>;
export declare const AssetEmissionSourceCategorySchema: z.ZodEnum<["STATIONARY_COMBUSTION", "FUGITIVE_EMISSIONS", "PROCESS_EMISSIONS"]>;
export declare const AssetConditionIndexSchema: z.ZodEnum<["NEW", "GOOD", "FAIR", "POOR"]>;
export declare const AssetRedundancyLevelSchema: z.ZodEnum<["N", "N+1", "2N"]>;
export type AssetCriticality = z.infer<typeof AssetCriticalitySchema>;
export type AssetEnergySource = z.infer<typeof AssetEnergySourceSchema>;
export type AssetGhgScope = z.infer<typeof AssetGhgScopeSchema>;
export type AssetEmissionSourceCategory = z.infer<typeof AssetEmissionSourceCategorySchema>;
export type AssetConditionIndex = z.infer<typeof AssetConditionIndexSchema>;
export type AssetRedundancyLevel = z.infer<typeof AssetRedundancyLevelSchema>;
export declare const AssetDTOSchema: z.ZodObject<{
    id: z.ZodUnion<[z.ZodString, z.ZodString]>;
    organizationId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    regionId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    branchId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    buildingId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    /** Mock UI: permite vacío y se sustituye por placeholder estable. */
    costCenterId: z.ZodEffects<z.ZodUnion<[z.ZodString, z.ZodString]>, string, unknown>;
    name: z.ZodString;
    assetTag: z.ZodOptional<z.ZodString>;
    barcode: z.ZodOptional<z.ZodString>;
    type: z.ZodEnum<["HVAC", "CHILLER", "MOTOR", "BOILER", "LIGHTING", "INDUSTRIAL_MACHINERY", "COMPRESSED_AIR"]>;
    status: z.ZodEnum<["ACTIVE", "INACTIVE", "MAINTENANCE"]>;
    criticality: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "MISSION_CRITICAL"]>>;
    manufacturer: z.ZodOptional<z.ZodString>;
    model: z.ZodOptional<z.ZodString>;
    serialNumber: z.ZodOptional<z.ZodString>;
    installationDate: z.ZodString;
    usefulLifeYears: z.ZodNumber;
    decommissionDate: z.ZodOptional<z.ZodString>;
    isSignificantEnergyUse: z.ZodDefault<z.ZodBoolean>;
    nominalPowerKw: z.ZodNumber;
    standbyPowerKw: z.ZodOptional<z.ZodNumber>;
    energySource: z.ZodEnum<["ELECTRICITY", "NATURAL_GAS", "DIESEL", "BIOMASS", "STEAM", "HYDROGEN"]>;
    nominalEfficiency: z.ZodNumber;
    dutyCycleExpected: z.ZodDefault<z.ZodNumber>;
    powerFactorTarget: z.ZodDefault<z.ZodNumber>;
    ghgScope: z.ZodEnum<["SCOPE_1", "SCOPE_2", "SCOPE_3"]>;
    emissionSourceCategory: z.ZodEnum<["STATIONARY_COMBUSTION", "FUGITIVE_EMISSIONS", "PROCESS_EMISSIONS"]>;
    fuelType: z.ZodOptional<z.ZodString>;
    biogenicFraction: z.ZodDefault<z.ZodNumber>;
    refrigerantGasType: z.ZodOptional<z.ZodString>;
    refrigerantChargeKg: z.ZodOptional<z.ZodNumber>;
    refrigerantGWP: z.ZodOptional<z.ZodNumber>;
    annualLeakageRateExpected: z.ZodDefault<z.ZodNumber>;
    meterId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    cloudDeviceId: z.ZodOptional<z.ZodString>;
    telemetryTopic: z.ZodOptional<z.ZodString>;
    isVirtualAsset: z.ZodDefault<z.ZodBoolean>;
    dataQualityScore: z.ZodDefault<z.ZodNumber>;
    lastMaintenanceDate: z.ZodOptional<z.ZodString>;
    nextMaintenanceDate: z.ZodOptional<z.ZodString>;
    maintenanceVendor: z.ZodOptional<z.ZodString>;
    conditionIndex: z.ZodEnum<["NEW", "GOOD", "FAIR", "POOR"]>;
    efficiencyDegradationFactor: z.ZodDefault<z.ZodNumber>;
    redundancyLevel: z.ZodDefault<z.ZodEnum<["N", "N+1", "2N"]>>;
    mtbfHours: z.ZodOptional<z.ZodNumber>;
    tags: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "HVAC" | "CHILLER" | "MOTOR" | "BOILER" | "LIGHTING" | "INDUSTRIAL_MACHINERY" | "COMPRESSED_AIR";
    status: "INACTIVE" | "MAINTENANCE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    regionId: string;
    tags: Record<string, string>;
    costCenterId: string;
    branchId: string;
    buildingId: string;
    criticality: "HIGH" | "LOW" | "MEDIUM" | "MISSION_CRITICAL";
    installationDate: string;
    usefulLifeYears: number;
    isSignificantEnergyUse: boolean;
    nominalPowerKw: number;
    energySource: "ELECTRICITY" | "DIESEL" | "STEAM" | "NATURAL_GAS" | "BIOMASS" | "HYDROGEN";
    nominalEfficiency: number;
    dutyCycleExpected: number;
    powerFactorTarget: number;
    ghgScope: "SCOPE_1" | "SCOPE_2" | "SCOPE_3";
    emissionSourceCategory: "STATIONARY_COMBUSTION" | "FUGITIVE_EMISSIONS" | "PROCESS_EMISSIONS";
    biogenicFraction: number;
    annualLeakageRateExpected: number;
    isVirtualAsset: boolean;
    dataQualityScore: number;
    conditionIndex: "POOR" | "NEW" | "GOOD" | "FAIR";
    efficiencyDegradationFactor: number;
    redundancyLevel: "N" | "N+1" | "2N";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    assetTag?: string | undefined;
    barcode?: string | undefined;
    manufacturer?: string | undefined;
    model?: string | undefined;
    serialNumber?: string | undefined;
    decommissionDate?: string | undefined;
    standbyPowerKw?: number | undefined;
    fuelType?: string | undefined;
    refrigerantGasType?: string | undefined;
    refrigerantChargeKg?: number | undefined;
    refrigerantGWP?: number | undefined;
    meterId?: string | undefined;
    cloudDeviceId?: string | undefined;
    telemetryTopic?: string | undefined;
    lastMaintenanceDate?: string | undefined;
    nextMaintenanceDate?: string | undefined;
    maintenanceVendor?: string | undefined;
    mtbfHours?: number | undefined;
}, {
    type: "HVAC" | "CHILLER" | "MOTOR" | "BOILER" | "LIGHTING" | "INDUSTRIAL_MACHINERY" | "COMPRESSED_AIR";
    status: "INACTIVE" | "MAINTENANCE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    regionId: string;
    branchId: string;
    buildingId: string;
    installationDate: string;
    usefulLifeYears: number;
    nominalPowerKw: number;
    energySource: "ELECTRICITY" | "DIESEL" | "STEAM" | "NATURAL_GAS" | "BIOMASS" | "HYDROGEN";
    nominalEfficiency: number;
    ghgScope: "SCOPE_1" | "SCOPE_2" | "SCOPE_3";
    emissionSourceCategory: "STATIONARY_COMBUSTION" | "FUGITIVE_EMISSIONS" | "PROCESS_EMISSIONS";
    conditionIndex: "POOR" | "NEW" | "GOOD" | "FAIR";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    costCenterId?: unknown;
    assetTag?: string | undefined;
    barcode?: string | undefined;
    criticality?: "HIGH" | "LOW" | "MEDIUM" | "MISSION_CRITICAL" | undefined;
    manufacturer?: string | undefined;
    model?: string | undefined;
    serialNumber?: string | undefined;
    decommissionDate?: string | undefined;
    isSignificantEnergyUse?: boolean | undefined;
    standbyPowerKw?: number | undefined;
    dutyCycleExpected?: number | undefined;
    powerFactorTarget?: number | undefined;
    fuelType?: string | undefined;
    biogenicFraction?: number | undefined;
    refrigerantGasType?: string | undefined;
    refrigerantChargeKg?: number | undefined;
    refrigerantGWP?: number | undefined;
    annualLeakageRateExpected?: number | undefined;
    meterId?: string | undefined;
    cloudDeviceId?: string | undefined;
    telemetryTopic?: string | undefined;
    isVirtualAsset?: boolean | undefined;
    dataQualityScore?: number | undefined;
    lastMaintenanceDate?: string | undefined;
    nextMaintenanceDate?: string | undefined;
    maintenanceVendor?: string | undefined;
    efficiencyDegradationFactor?: number | undefined;
    redundancyLevel?: "N" | "N+1" | "2N" | undefined;
    mtbfHours?: number | undefined;
}>;
export declare class AssetDTO {
    readonly id: string;
    readonly organizationId: string;
    readonly regionId: string;
    readonly branchId: string;
    readonly buildingId: string;
    readonly costCenterId: string;
    readonly name: string;
    readonly assetTag?: string;
    readonly barcode?: string;
    readonly type: z.infer<typeof AssetTypeSchema>;
    readonly status: z.infer<typeof AssetLifecycleStatusSchema>;
    readonly criticality: z.infer<typeof AssetCriticalitySchema>;
    readonly manufacturer?: string;
    readonly model?: string;
    readonly serialNumber?: string;
    readonly installationDate: string;
    readonly usefulLifeYears: number;
    readonly decommissionDate?: string;
    readonly isSignificantEnergyUse: boolean;
    readonly nominalPowerKw: number;
    readonly standbyPowerKw?: number;
    readonly energySource: z.infer<typeof AssetEnergySourceSchema>;
    readonly nominalEfficiency: number;
    readonly dutyCycleExpected: number;
    readonly powerFactorTarget: number;
    readonly ghgScope: z.infer<typeof AssetGhgScopeSchema>;
    readonly emissionSourceCategory: z.infer<typeof AssetEmissionSourceCategorySchema>;
    readonly fuelType?: string;
    readonly biogenicFraction: number;
    readonly refrigerantGasType?: string;
    readonly refrigerantChargeKg?: number;
    readonly refrigerantGWP?: number;
    readonly annualLeakageRateExpected: number;
    readonly meterId?: string;
    readonly cloudDeviceId?: string;
    readonly telemetryTopic?: string;
    readonly isVirtualAsset: boolean;
    readonly dataQualityScore: number;
    readonly lastMaintenanceDate?: string;
    readonly nextMaintenanceDate?: string;
    readonly maintenanceVendor?: string;
    readonly conditionIndex: z.infer<typeof AssetConditionIndexSchema>;
    readonly efficiencyDegradationFactor: number;
    readonly redundancyLevel: z.infer<typeof AssetRedundancyLevelSchema>;
    readonly mtbfHours?: number;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, organizationId: string, regionId: string, branchId: string, buildingId: string, costCenterId: string, name: string, assetTag: string | null | undefined, barcode: string | null | undefined, type: z.infer<typeof AssetTypeSchema>, status: z.infer<typeof AssetLifecycleStatusSchema>, criticality: z.infer<typeof AssetCriticalitySchema> | null | undefined, manufacturer: string | null | undefined, model: string | null | undefined, serialNumber: string | null | undefined, installationDate: string, usefulLifeYears: number, decommissionDate: string | null | undefined, isSignificantEnergyUse: boolean | null | undefined, nominalPowerKw: number, standbyPowerKw: number | null | undefined, energySource: z.infer<typeof AssetEnergySourceSchema>, nominalEfficiency: number, dutyCycleExpected: number | null | undefined, powerFactorTarget: number | null | undefined, ghgScope: z.infer<typeof AssetGhgScopeSchema>, emissionSourceCategory: z.infer<typeof AssetEmissionSourceCategorySchema>, fuelType: string | null | undefined, biogenicFraction: number | null | undefined, refrigerantGasType: string | null | undefined, refrigerantChargeKg: number | null | undefined, refrigerantGWP: number | null | undefined, annualLeakageRateExpected: number | null | undefined, meterId: string | null | undefined, cloudDeviceId: string | null | undefined, telemetryTopic: string | null | undefined, isVirtualAsset: boolean | null | undefined, dataQualityScore: number | null | undefined, lastMaintenanceDate: string | null | undefined, nextMaintenanceDate: string | null | undefined, maintenanceVendor: string | null | undefined, conditionIndex: z.infer<typeof AssetConditionIndexSchema>, efficiencyDegradationFactor: number | null | undefined, redundancyLevel: z.infer<typeof AssetRedundancyLevelSchema> | null | undefined, mtbfHours: number | null | undefined, tags: Record<string, string> | null | undefined, createdAt?: string, updatedAt?: string);
}
export type AssetDTOInput = z.infer<typeof AssetDTOSchema>;
export declare const parseAssetDTO: (input: unknown) => AssetDTO;
export declare const safeParseAssetDTO: (input: unknown) => z.SafeParseReturnType<{
    type: "HVAC" | "CHILLER" | "MOTOR" | "BOILER" | "LIGHTING" | "INDUSTRIAL_MACHINERY" | "COMPRESSED_AIR";
    status: "INACTIVE" | "MAINTENANCE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    regionId: string;
    branchId: string;
    buildingId: string;
    installationDate: string;
    usefulLifeYears: number;
    nominalPowerKw: number;
    energySource: "ELECTRICITY" | "DIESEL" | "STEAM" | "NATURAL_GAS" | "BIOMASS" | "HYDROGEN";
    nominalEfficiency: number;
    ghgScope: "SCOPE_1" | "SCOPE_2" | "SCOPE_3";
    emissionSourceCategory: "STATIONARY_COMBUSTION" | "FUGITIVE_EMISSIONS" | "PROCESS_EMISSIONS";
    conditionIndex: "POOR" | "NEW" | "GOOD" | "FAIR";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    costCenterId?: unknown;
    assetTag?: string | undefined;
    barcode?: string | undefined;
    criticality?: "HIGH" | "LOW" | "MEDIUM" | "MISSION_CRITICAL" | undefined;
    manufacturer?: string | undefined;
    model?: string | undefined;
    serialNumber?: string | undefined;
    decommissionDate?: string | undefined;
    isSignificantEnergyUse?: boolean | undefined;
    standbyPowerKw?: number | undefined;
    dutyCycleExpected?: number | undefined;
    powerFactorTarget?: number | undefined;
    fuelType?: string | undefined;
    biogenicFraction?: number | undefined;
    refrigerantGasType?: string | undefined;
    refrigerantChargeKg?: number | undefined;
    refrigerantGWP?: number | undefined;
    annualLeakageRateExpected?: number | undefined;
    meterId?: string | undefined;
    cloudDeviceId?: string | undefined;
    telemetryTopic?: string | undefined;
    isVirtualAsset?: boolean | undefined;
    dataQualityScore?: number | undefined;
    lastMaintenanceDate?: string | undefined;
    nextMaintenanceDate?: string | undefined;
    maintenanceVendor?: string | undefined;
    efficiencyDegradationFactor?: number | undefined;
    redundancyLevel?: "N" | "N+1" | "2N" | undefined;
    mtbfHours?: number | undefined;
}, {
    type: "HVAC" | "CHILLER" | "MOTOR" | "BOILER" | "LIGHTING" | "INDUSTRIAL_MACHINERY" | "COMPRESSED_AIR";
    status: "INACTIVE" | "MAINTENANCE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    regionId: string;
    tags: Record<string, string>;
    costCenterId: string;
    branchId: string;
    buildingId: string;
    criticality: "HIGH" | "LOW" | "MEDIUM" | "MISSION_CRITICAL";
    installationDate: string;
    usefulLifeYears: number;
    isSignificantEnergyUse: boolean;
    nominalPowerKw: number;
    energySource: "ELECTRICITY" | "DIESEL" | "STEAM" | "NATURAL_GAS" | "BIOMASS" | "HYDROGEN";
    nominalEfficiency: number;
    dutyCycleExpected: number;
    powerFactorTarget: number;
    ghgScope: "SCOPE_1" | "SCOPE_2" | "SCOPE_3";
    emissionSourceCategory: "STATIONARY_COMBUSTION" | "FUGITIVE_EMISSIONS" | "PROCESS_EMISSIONS";
    biogenicFraction: number;
    annualLeakageRateExpected: number;
    isVirtualAsset: boolean;
    dataQualityScore: number;
    conditionIndex: "POOR" | "NEW" | "GOOD" | "FAIR";
    efficiencyDegradationFactor: number;
    redundancyLevel: "N" | "N+1" | "2N";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    assetTag?: string | undefined;
    barcode?: string | undefined;
    manufacturer?: string | undefined;
    model?: string | undefined;
    serialNumber?: string | undefined;
    decommissionDate?: string | undefined;
    standbyPowerKw?: number | undefined;
    fuelType?: string | undefined;
    refrigerantGasType?: string | undefined;
    refrigerantChargeKg?: number | undefined;
    refrigerantGWP?: number | undefined;
    meterId?: string | undefined;
    cloudDeviceId?: string | undefined;
    telemetryTopic?: string | undefined;
    lastMaintenanceDate?: string | undefined;
    nextMaintenanceDate?: string | undefined;
    maintenanceVendor?: string | undefined;
    mtbfHours?: number | undefined;
}>;
//# sourceMappingURL=asset.dto.d.ts.map