import { z } from 'zod';
/** Tipo de entidad monitoreada. */
export declare const AlertRuleEntityTypeSchema: z.ZodEnum<["METER", "ASSET", "BUILDING", "COST_CENTER", "TARIFF"]>;
/** Familia de alerta (motor de detección). */
export declare const AlertRuleDetectionTypeSchema: z.ZodEnum<["OVER_CONSUMPTION", "LEAK", "POWER_QUALITY", "CONNECTIVITY", "BUDGET_EXCEEDED"]>;
export declare const AlertRuleThresholdOperatorSymbolSchema: z.ZodEnum<[">", "<", ">=", "<=", "==", "!="]>;
export declare const AlertRuleAggregationMethodSchema: z.ZodEnum<["SUM", "AVG", "MAX", "MIN", "LAST", "DELTA"]>;
export declare const AlertRulePrioritySchema: z.ZodEnum<["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]>;
export declare const AlertRuleRuleStatusSchema: z.ZodEnum<["ACTIVE", "INACTIVE", "MAINTENANCE", "MUTED"]>;
export declare const AlertRuleMonitorScopeSchema: z.ZodEnum<["WORKING_HOURS", "NON_WORKING_HOURS", "24_7"]>;
export declare const AlertRuleNotificationChannelSchema: z.ZodEnum<["EMAIL", "SMS", "PUSH", "WEBHOOK", "WHATSAPP", "SLACK"]>;
export declare function generateAlertRuleId(): string;
export declare const AlertRuleDTOSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    orgId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    branchId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    entityId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    entityType: z.ZodEffects<z.ZodEnum<["METER", "ASSET", "BUILDING", "COST_CENTER", "TARIFF"]>, "BUILDING" | "METER" | "ASSET" | "COST_CENTER" | "TARIFF", unknown>;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    alertType: z.ZodEffects<z.ZodEnum<["OVER_CONSUMPTION", "LEAK", "POWER_QUALITY", "CONNECTIVITY", "BUDGET_EXCEEDED"]>, "OVER_CONSUMPTION" | "LEAK" | "POWER_QUALITY" | "CONNECTIVITY" | "BUDGET_EXCEEDED", unknown>;
    metricName: z.ZodEffects<z.ZodString, string, unknown>;
    operator: z.ZodEffects<z.ZodEnum<[">", "<", ">=", "<=", "==", "!="]>, ">" | "<" | ">=" | "<=" | "==" | "!=", unknown>;
    threshold: z.ZodNumber;
    aggregationWindowMinutes: z.ZodDefault<z.ZodNumber>;
    aggregationMethod: z.ZodDefault<z.ZodEnum<["SUM", "AVG", "MAX", "MIN", "LAST", "DELTA"]>>;
    occurrencesBeforeTrigger: z.ZodDefault<z.ZodNumber>;
    priority: z.ZodEffects<z.ZodEnum<["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]>, "HIGH" | "CRITICAL" | "LOW" | "MEDIUM" | "INFO", unknown>;
    status: z.ZodEffects<z.ZodEnum<["ACTIVE", "INACTIVE", "MAINTENANCE", "MUTED"]>, "INACTIVE" | "MAINTENANCE" | "ACTIVE" | "MUTED", unknown>;
    severityScore: z.ZodDefault<z.ZodNumber>;
    notificationChannels: z.ZodDefault<z.ZodArray<z.ZodEnum<["EMAIL", "SMS", "PUSH", "WEBHOOK", "WHATSAPP", "SLACK"]>, "many">>;
    recipients: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    coolDownMinutes: z.ZodDefault<z.ZodNumber>;
    autoAcknowledge: z.ZodDefault<z.ZodBoolean>;
    monitorScope: z.ZodEffects<z.ZodEnum<["WORKING_HOURS", "NON_WORKING_HOURS", "24_7"]>, "WORKING_HOURS" | "NON_WORKING_HOURS" | "24_7", unknown>;
    calendarId: z.ZodOptional<z.ZodString>;
    webhookActionUrl: z.ZodOptional<z.ZodString>;
    recoveryThreshold: z.ZodOptional<z.ZodNumber>;
    tags: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "INACTIVE" | "MAINTENANCE" | "ACTIVE" | "MUTED";
    name: string;
    tags: Record<string, string>;
    branchId: string;
    orgId: string;
    entityId: string;
    entityType: "BUILDING" | "METER" | "ASSET" | "COST_CENTER" | "TARIFF";
    alertType: "OVER_CONSUMPTION" | "LEAK" | "POWER_QUALITY" | "CONNECTIVITY" | "BUDGET_EXCEEDED";
    metricName: string;
    operator: ">" | "<" | ">=" | "<=" | "==" | "!=";
    threshold: number;
    aggregationWindowMinutes: number;
    aggregationMethod: "SUM" | "AVG" | "MAX" | "MIN" | "LAST" | "DELTA";
    occurrencesBeforeTrigger: number;
    priority: "HIGH" | "CRITICAL" | "LOW" | "MEDIUM" | "INFO";
    severityScore: number;
    notificationChannels: ("EMAIL" | "SMS" | "PUSH" | "WEBHOOK" | "WHATSAPP" | "SLACK")[];
    recipients: string[];
    coolDownMinutes: number;
    autoAcknowledge: boolean;
    monitorScope: "WORKING_HOURS" | "NON_WORKING_HOURS" | "24_7";
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    description?: string | undefined;
    calendarId?: string | undefined;
    webhookActionUrl?: string | undefined;
    recoveryThreshold?: number | undefined;
}, {
    name: string;
    branchId: string;
    orgId: string;
    entityId: string;
    threshold: number;
    status?: unknown;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    description?: string | undefined;
    tags?: Record<string, string> | undefined;
    entityType?: unknown;
    alertType?: unknown;
    metricName?: unknown;
    operator?: unknown;
    aggregationWindowMinutes?: number | undefined;
    aggregationMethod?: "SUM" | "AVG" | "MAX" | "MIN" | "LAST" | "DELTA" | undefined;
    occurrencesBeforeTrigger?: number | undefined;
    priority?: unknown;
    severityScore?: number | undefined;
    notificationChannels?: ("EMAIL" | "SMS" | "PUSH" | "WEBHOOK" | "WHATSAPP" | "SLACK")[] | undefined;
    recipients?: string[] | undefined;
    coolDownMinutes?: number | undefined;
    autoAcknowledge?: boolean | undefined;
    monitorScope?: unknown;
    calendarId?: string | undefined;
    webhookActionUrl?: string | undefined;
    recoveryThreshold?: number | undefined;
}>;
export type AlertRuleDTOInput = z.infer<typeof AlertRuleDTOSchema>;
export declare class AlertRuleDTO {
    readonly id: string;
    readonly orgId: string;
    readonly branchId: string;
    readonly entityId: string;
    readonly entityType: z.infer<typeof AlertRuleEntityTypeSchema>;
    readonly name: string;
    readonly description?: string;
    readonly alertType: z.infer<typeof AlertRuleDetectionTypeSchema>;
    readonly metricName: string;
    readonly operator: z.infer<typeof AlertRuleThresholdOperatorSymbolSchema>;
    readonly threshold: number;
    readonly aggregationWindowMinutes: number;
    readonly aggregationMethod: z.infer<typeof AlertRuleAggregationMethodSchema>;
    readonly occurrencesBeforeTrigger: number;
    readonly priority: z.infer<typeof AlertRulePrioritySchema>;
    readonly status: z.infer<typeof AlertRuleRuleStatusSchema>;
    readonly severityScore: number;
    readonly notificationChannels: z.infer<typeof AlertRuleNotificationChannelSchema>[];
    readonly recipients: string[];
    readonly coolDownMinutes: number;
    readonly autoAcknowledge: boolean;
    readonly monitorScope: z.infer<typeof AlertRuleMonitorScopeSchema>;
    readonly calendarId?: string;
    readonly webhookActionUrl?: string;
    readonly recoveryThreshold?: number;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, orgId: string, branchId: string, entityId: string, entityType: z.infer<typeof AlertRuleEntityTypeSchema>, name: string, description: string | null | undefined, alertType: z.infer<typeof AlertRuleDetectionTypeSchema>, metricName: string, operator: z.infer<typeof AlertRuleThresholdOperatorSymbolSchema>, threshold: number, aggregationWindowMinutes: number | null | undefined, aggregationMethod: z.infer<typeof AlertRuleAggregationMethodSchema>, occurrencesBeforeTrigger: number | null | undefined, priority: z.infer<typeof AlertRulePrioritySchema>, status: z.infer<typeof AlertRuleRuleStatusSchema>, severityScore: number | null | undefined, notificationChannels: readonly z.infer<typeof AlertRuleNotificationChannelSchema>[] | null | undefined, recipients: readonly string[] | null | undefined, coolDownMinutes: number | null | undefined, autoAcknowledge: boolean | null | undefined, monitorScope: z.infer<typeof AlertRuleMonitorScopeSchema>, calendarId: string | null | undefined, webhookActionUrl: string | null | undefined, recoveryThreshold: number | null | undefined, tags: Record<string, string> | null | undefined, createdAt?: string, updatedAt?: string);
}
export declare const parseAlertRuleDTO: (input: unknown) => AlertRuleDTO;
export declare const safeParseAlertRuleDTO: (input: unknown) => z.SafeParseReturnType<{
    name: string;
    branchId: string;
    orgId: string;
    entityId: string;
    threshold: number;
    status?: unknown;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    description?: string | undefined;
    tags?: Record<string, string> | undefined;
    entityType?: unknown;
    alertType?: unknown;
    metricName?: unknown;
    operator?: unknown;
    aggregationWindowMinutes?: number | undefined;
    aggregationMethod?: "SUM" | "AVG" | "MAX" | "MIN" | "LAST" | "DELTA" | undefined;
    occurrencesBeforeTrigger?: number | undefined;
    priority?: unknown;
    severityScore?: number | undefined;
    notificationChannels?: ("EMAIL" | "SMS" | "PUSH" | "WEBHOOK" | "WHATSAPP" | "SLACK")[] | undefined;
    recipients?: string[] | undefined;
    coolDownMinutes?: number | undefined;
    autoAcknowledge?: boolean | undefined;
    monitorScope?: unknown;
    calendarId?: string | undefined;
    webhookActionUrl?: string | undefined;
    recoveryThreshold?: number | undefined;
}, {
    status: "INACTIVE" | "MAINTENANCE" | "ACTIVE" | "MUTED";
    name: string;
    tags: Record<string, string>;
    branchId: string;
    orgId: string;
    entityId: string;
    entityType: "BUILDING" | "METER" | "ASSET" | "COST_CENTER" | "TARIFF";
    alertType: "OVER_CONSUMPTION" | "LEAK" | "POWER_QUALITY" | "CONNECTIVITY" | "BUDGET_EXCEEDED";
    metricName: string;
    operator: ">" | "<" | ">=" | "<=" | "==" | "!=";
    threshold: number;
    aggregationWindowMinutes: number;
    aggregationMethod: "SUM" | "AVG" | "MAX" | "MIN" | "LAST" | "DELTA";
    occurrencesBeforeTrigger: number;
    priority: "HIGH" | "CRITICAL" | "LOW" | "MEDIUM" | "INFO";
    severityScore: number;
    notificationChannels: ("EMAIL" | "SMS" | "PUSH" | "WEBHOOK" | "WHATSAPP" | "SLACK")[];
    recipients: string[];
    coolDownMinutes: number;
    autoAcknowledge: boolean;
    monitorScope: "WORKING_HOURS" | "NON_WORKING_HOURS" | "24_7";
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    description?: string | undefined;
    calendarId?: string | undefined;
    webhookActionUrl?: string | undefined;
    recoveryThreshold?: number | undefined;
}>;
//# sourceMappingURL=alert-rule.dto.d.ts.map