import { z } from 'zod';
import { CostAllocationMethodSchema, LifecycleStatusSchema } from '../common/graphql-setup-enums.js';
export declare const CostCenterTypeSchema: z.ZodEnum<["DEPARTMENT", "PROJECT", "SERVICE", "OPERATIONAL_UNIT"]>;
export type CostCenterType = z.infer<typeof CostCenterTypeSchema>;
export declare const CostCenterForecastModelSchema: z.ZodEnum<["LINEAR", "ML_PROPHET", "ARIMA", "STRICT_BUDGET"]>;
export type CostCenterForecastModel = z.infer<typeof CostCenterForecastModelSchema>;
export declare const CostCenterDTOSchema: z.ZodObject<{
    id: z.ZodUnion<[z.ZodString, z.ZodString]>;
    organizationId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    name: z.ZodString;
    externalId: z.ZodOptional<z.ZodString>;
    parentId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    branchId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    buildingId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    annualBudget: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    budgetThresholdAlert: z.ZodDefault<z.ZodNumber>;
    carbonBudgetTons: z.ZodOptional<z.ZodNumber>;
    carbonShadowPrice: z.ZodOptional<z.ZodNumber>;
    budgetSensitivityIndex: z.ZodDefault<z.ZodNumber>;
    fiscalYear: z.ZodDefault<z.ZodNumber>;
    headcount: z.ZodOptional<z.ZodNumber>;
    floorAreaSqm: z.ZodOptional<z.ZodNumber>;
    productionUnitName: z.ZodOptional<z.ZodString>;
    targetIntensity: z.ZodOptional<z.ZodNumber>;
    /** % meta renovable objetivo (0–100). */
    renewableEnergyTarget: z.ZodDefault<z.ZodNumber>;
    allocationMethod: z.ZodEnum<["FIXED", "PERCENTAGE", "SQUARE_METERS"]>;
    percentage: z.ZodDefault<z.ZodNumber>;
    iscommon: z.ZodDefault<z.ZodBoolean>;
    allocationLastReviewDate: z.ZodOptional<z.ZodString>;
    approvedBy: z.ZodOptional<z.ZodString>;
    type: z.ZodEnum<["DEPARTMENT", "PROJECT", "SERVICE", "OPERATIONAL_UNIT"]>;
    forecastModel: z.ZodEnum<["LINEAR", "ML_PROPHET", "ARIMA", "STRICT_BUDGET"]>;
    managerEmail: z.ZodOptional<z.ZodString>;
    operatingHoursId: z.ZodOptional<z.ZodString>;
    status: z.ZodEnum<["ACTIVE", "INACTIVE"]>;
    tags: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "DEPARTMENT" | "PROJECT" | "SERVICE" | "OPERATIONAL_UNIT";
    status: "INACTIVE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    tags: Record<string, string>;
    annualBudget: number;
    currency: string;
    budgetThresholdAlert: number;
    budgetSensitivityIndex: number;
    fiscalYear: number;
    renewableEnergyTarget: number;
    allocationMethod: "FIXED" | "PERCENTAGE" | "SQUARE_METERS";
    percentage: number;
    iscommon: boolean;
    forecastModel: "LINEAR" | "ML_PROPHET" | "ARIMA" | "STRICT_BUDGET";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    branchId?: string | undefined;
    externalId?: string | undefined;
    parentId?: string | undefined;
    buildingId?: string | undefined;
    carbonBudgetTons?: number | undefined;
    carbonShadowPrice?: number | undefined;
    headcount?: number | undefined;
    floorAreaSqm?: number | undefined;
    productionUnitName?: string | undefined;
    targetIntensity?: number | undefined;
    allocationLastReviewDate?: string | undefined;
    approvedBy?: string | undefined;
    managerEmail?: string | undefined;
    operatingHoursId?: string | undefined;
}, {
    type: "DEPARTMENT" | "PROJECT" | "SERVICE" | "OPERATIONAL_UNIT";
    status: "INACTIVE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    annualBudget: number;
    allocationMethod: "FIXED" | "PERCENTAGE" | "SQUARE_METERS";
    forecastModel: "LINEAR" | "ML_PROPHET" | "ARIMA" | "STRICT_BUDGET";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    branchId?: string | undefined;
    externalId?: string | undefined;
    parentId?: string | undefined;
    buildingId?: string | undefined;
    currency?: string | undefined;
    budgetThresholdAlert?: number | undefined;
    carbonBudgetTons?: number | undefined;
    carbonShadowPrice?: number | undefined;
    budgetSensitivityIndex?: number | undefined;
    fiscalYear?: number | undefined;
    headcount?: number | undefined;
    floorAreaSqm?: number | undefined;
    productionUnitName?: string | undefined;
    targetIntensity?: number | undefined;
    renewableEnergyTarget?: number | undefined;
    percentage?: number | undefined;
    iscommon?: boolean | undefined;
    allocationLastReviewDate?: string | undefined;
    approvedBy?: string | undefined;
    managerEmail?: string | undefined;
    operatingHoursId?: string | undefined;
}>;
export declare class CostCenterDTO {
    readonly id: string;
    readonly organizationId: string;
    readonly name: string;
    readonly externalId?: string;
    readonly parentId?: string;
    readonly branchId?: string;
    readonly buildingId?: string;
    readonly annualBudget: number;
    readonly currency: string;
    readonly budgetThresholdAlert: number;
    readonly carbonBudgetTons?: number;
    readonly carbonShadowPrice?: number;
    readonly budgetSensitivityIndex: number;
    readonly fiscalYear: number;
    readonly headcount?: number;
    readonly floorAreaSqm?: number;
    readonly productionUnitName?: string;
    readonly targetIntensity?: number;
    readonly renewableEnergyTarget: number;
    readonly allocationMethod: z.infer<typeof CostAllocationMethodSchema>;
    readonly percentage: number;
    readonly iscommon: boolean;
    readonly allocationLastReviewDate?: string;
    readonly approvedBy?: string;
    readonly type: z.infer<typeof CostCenterTypeSchema>;
    readonly forecastModel: z.infer<typeof CostCenterForecastModelSchema>;
    readonly managerEmail?: string;
    readonly operatingHoursId?: string;
    readonly status: z.infer<typeof LifecycleStatusSchema>;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, organizationId: string, name: string, externalId: string | null | undefined, parentId: string | null | undefined, branchId: string | null | undefined, buildingId: string | null | undefined, annualBudget: number, currency: string | null | undefined, budgetThresholdAlert: number | null | undefined, carbonBudgetTons: number | null | undefined, carbonShadowPrice: number | null | undefined, budgetSensitivityIndex: number | null | undefined, fiscalYear: number | null | undefined, headcount: number | null | undefined, floorAreaSqm: number | null | undefined, productionUnitName: string | null | undefined, targetIntensity: number | null | undefined, renewableEnergyTarget: number | null | undefined, allocationMethod: z.infer<typeof CostAllocationMethodSchema>, percentage: number | null | undefined, iscommon: boolean | null | undefined, allocationLastReviewDate: string | null | undefined, approvedBy: string | null | undefined, type: z.infer<typeof CostCenterTypeSchema>, forecastModel: z.infer<typeof CostCenterForecastModelSchema>, managerEmail: string | null | undefined, operatingHoursId: string | null | undefined, status: z.infer<typeof LifecycleStatusSchema>, tags: Record<string, string> | null | undefined, createdAt?: string, updatedAt?: string);
}
export type CostCenterDTOInput = z.infer<typeof CostCenterDTOSchema>;
export declare const parseCostCenterDTO: (input: unknown) => CostCenterDTO;
export declare const safeParseCostCenterDTO: (input: unknown) => z.SafeParseReturnType<{
    type: "DEPARTMENT" | "PROJECT" | "SERVICE" | "OPERATIONAL_UNIT";
    status: "INACTIVE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    annualBudget: number;
    allocationMethod: "FIXED" | "PERCENTAGE" | "SQUARE_METERS";
    forecastModel: "LINEAR" | "ML_PROPHET" | "ARIMA" | "STRICT_BUDGET";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    branchId?: string | undefined;
    externalId?: string | undefined;
    parentId?: string | undefined;
    buildingId?: string | undefined;
    currency?: string | undefined;
    budgetThresholdAlert?: number | undefined;
    carbonBudgetTons?: number | undefined;
    carbonShadowPrice?: number | undefined;
    budgetSensitivityIndex?: number | undefined;
    fiscalYear?: number | undefined;
    headcount?: number | undefined;
    floorAreaSqm?: number | undefined;
    productionUnitName?: string | undefined;
    targetIntensity?: number | undefined;
    renewableEnergyTarget?: number | undefined;
    percentage?: number | undefined;
    iscommon?: boolean | undefined;
    allocationLastReviewDate?: string | undefined;
    approvedBy?: string | undefined;
    managerEmail?: string | undefined;
    operatingHoursId?: string | undefined;
}, {
    type: "DEPARTMENT" | "PROJECT" | "SERVICE" | "OPERATIONAL_UNIT";
    status: "INACTIVE" | "ACTIVE";
    name: string;
    id: string;
    organizationId: string;
    tags: Record<string, string>;
    annualBudget: number;
    currency: string;
    budgetThresholdAlert: number;
    budgetSensitivityIndex: number;
    fiscalYear: number;
    renewableEnergyTarget: number;
    allocationMethod: "FIXED" | "PERCENTAGE" | "SQUARE_METERS";
    percentage: number;
    iscommon: boolean;
    forecastModel: "LINEAR" | "ML_PROPHET" | "ARIMA" | "STRICT_BUDGET";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    branchId?: string | undefined;
    externalId?: string | undefined;
    parentId?: string | undefined;
    buildingId?: string | undefined;
    carbonBudgetTons?: number | undefined;
    carbonShadowPrice?: number | undefined;
    headcount?: number | undefined;
    floorAreaSqm?: number | undefined;
    productionUnitName?: string | undefined;
    targetIntensity?: number | undefined;
    allocationLastReviewDate?: string | undefined;
    approvedBy?: string | undefined;
    managerEmail?: string | undefined;
    operatingHoursId?: string | undefined;
}>;
//# sourceMappingURL=cost-center.dto.d.ts.map