import { z } from 'zod';
import { MeterTypeSchema } from '../shared/domain-enums.js';    
import { MeterOperationalStatusSchema, MeterProtocolSchema } from '../shared/graphql-setup-enums.js';
export declare const MeterServiceTypeSchema: z.ZodEnum<["UTILITY", "SUBMETERING", "GENERATION"]>;
export declare const MeterUnitSchema: z.ZodEnum<["KWH", "M3", "GJ", "L", "BTU"]>;
export declare const MeterAccuracyClassSchema: z.ZodEnum<["0.2S", "0.5S", "1.0", "2.0"]>;
export declare const MeterCommunicationStatusSchema: z.ZodEnum<["ONLINE", "OFFLINE", "DEGRADED"]>;
export type MeterServiceType = z.infer<typeof MeterServiceTypeSchema>;
export type MeterUnit = z.infer<typeof MeterUnitSchema>;
export type MeterAccuracyClass = z.infer<typeof MeterAccuracyClassSchema>;
export type MeterCommunicationStatus = z.infer<typeof MeterCommunicationStatusSchema>;
export declare const MeterDTOSchema: z.ZodObject<{
    id: z.ZodUnion<[z.ZodString, z.ZodString]>;
    orgId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    regionId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    branchId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    buildingId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    name: z.ZodString;
    serialNumber: z.ZodString;
    internalTag: z.ZodOptional<z.ZodString>;
    meterType: z.ZodEnum<["ELECTRICITY", "WATER", "GAS", "THERMAL", "BTU"]>;
    serviceType: z.ZodDefault<z.ZodEnum<["UTILITY", "SUBMETERING", "GENERATION"]>>;
    unit: z.ZodDefault<z.ZodEnum<["KWH", "M3", "GJ", "L", "BTU"]>>;
    accuracyClass: z.ZodDefault<z.ZodEnum<["0.2S", "0.5S", "1.0", "2.0"]>>;
    multiplier: z.ZodDefault<z.ZodNumber>;
    loggingIntervalMinutes: z.ZodDefault<z.ZodNumber>;
    timeZone: z.ZodDefault<z.ZodString>;
    isMain: z.ZodDefault<z.ZodBoolean>;
    isNetMetering: z.ZodDefault<z.ZodBoolean>;
    meterLevel: z.ZodNumber;
    parentMeterId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    assetId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    status: z.ZodEnum<["ACTIVE", "INACTIVE", "FAULT"]>;
    communicationStatus: z.ZodDefault<z.ZodEnum<["ONLINE", "OFFLINE", "DEGRADED"]>>;
    lastCalibrationDate: z.ZodOptional<z.ZodString>;
    nextCalibrationDate: z.ZodOptional<z.ZodString>;
    monitorsPowerQuality: z.ZodDefault<z.ZodBoolean>;
    hasDataLogging: z.ZodDefault<z.ZodBoolean>;
    metrologicalSealNumber: z.ZodOptional<z.ZodString>;
    protocol: z.ZodEnum<["MQTT", "MODBUS", "BACNET", "M_BUS", "LORAWAN"]>;
    physicalAddress: z.ZodOptional<z.ZodString>;
    firmwareVersion: z.ZodOptional<z.ZodString>;
    isVirtual: z.ZodDefault<z.ZodBoolean>;
    virtualFormula: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "INACTIVE" | "ACTIVE" | "FAULT";
    name: string;
    id: string;
    regionId: string;
    tags: Record<string, string>;
    branchId: string;
    buildingId: string;
    serialNumber: string;
    orgId: string;
    meterType: "ELECTRICITY" | "GAS" | "WATER" | "THERMAL" | "BTU";
    serviceType: "UTILITY" | "SUBMETERING" | "GENERATION";
    unit: "BTU" | "KWH" | "M3" | "GJ" | "L";
    accuracyClass: "0.2S" | "0.5S" | "1.0" | "2.0";
    multiplier: number;
    loggingIntervalMinutes: number;
    timeZone: string;
    isMain: boolean;
    isNetMetering: boolean;
    meterLevel: number;
    communicationStatus: "DEGRADED" | "ONLINE" | "OFFLINE";
    monitorsPowerQuality: boolean;
    hasDataLogging: boolean;
    protocol: "MQTT" | "MODBUS" | "BACNET" | "M_BUS" | "LORAWAN";
    isVirtual: boolean;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    internalTag?: string | undefined;
    parentMeterId?: string | undefined;
    assetId?: string | undefined;
    lastCalibrationDate?: string | undefined;
    nextCalibrationDate?: string | undefined;
    metrologicalSealNumber?: string | undefined;
    physicalAddress?: string | undefined;
    firmwareVersion?: string | undefined;
    virtualFormula?: string | undefined;
}, {
    status: "INACTIVE" | "ACTIVE" | "FAULT";
    name: string;
    id: string;
    regionId: string;
    branchId: string;
    buildingId: string;
    serialNumber: string;
    orgId: string;
    meterType: "ELECTRICITY" | "GAS" | "WATER" | "THERMAL" | "BTU";
    meterLevel: number;
    protocol: "MQTT" | "MODBUS" | "BACNET" | "M_BUS" | "LORAWAN";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    internalTag?: string | undefined;
    serviceType?: "UTILITY" | "SUBMETERING" | "GENERATION" | undefined;
    unit?: "BTU" | "KWH" | "M3" | "GJ" | "L" | undefined;
    accuracyClass?: "0.2S" | "0.5S" | "1.0" | "2.0" | undefined;
    multiplier?: number | undefined;
    loggingIntervalMinutes?: number | undefined;
    timeZone?: string | undefined;
    isMain?: boolean | undefined;
    isNetMetering?: boolean | undefined;
    parentMeterId?: string | undefined;
    assetId?: string | undefined;
    communicationStatus?: "DEGRADED" | "ONLINE" | "OFFLINE" | undefined;
    lastCalibrationDate?: string | undefined;
    nextCalibrationDate?: string | undefined;
    monitorsPowerQuality?: boolean | undefined;
    hasDataLogging?: boolean | undefined;
    metrologicalSealNumber?: string | undefined;
    physicalAddress?: string | undefined;
    firmwareVersion?: string | undefined;
    isVirtual?: boolean | undefined;
    virtualFormula?: string | undefined;
}>;
export declare class MeterDTO {
    readonly id: string;
    readonly orgId: string;
    readonly regionId: string;
    readonly branchId: string;
    readonly buildingId: string;
    readonly name: string;
    readonly serialNumber: string;
    readonly internalTag?: string;
    readonly meterType: z.infer<typeof MeterTypeSchema>;
    readonly serviceType: z.infer<typeof MeterServiceTypeSchema>;
    readonly unit: z.infer<typeof MeterUnitSchema>;
    readonly accuracyClass: z.infer<typeof MeterAccuracyClassSchema>;
    readonly multiplier: number;
    readonly loggingIntervalMinutes: number;
    readonly timeZone: string;
    readonly isMain: boolean;
    readonly isNetMetering: boolean;
    readonly meterLevel: number;
    readonly parentMeterId?: string;
    readonly assetId?: string;
    readonly status: z.infer<typeof MeterOperationalStatusSchema>;
    readonly communicationStatus: z.infer<typeof MeterCommunicationStatusSchema>;
    readonly lastCalibrationDate?: string;
    readonly nextCalibrationDate?: string;
    readonly monitorsPowerQuality: boolean;
    readonly hasDataLogging: boolean;
    readonly metrologicalSealNumber?: string;
    readonly protocol: z.infer<typeof MeterProtocolSchema>;
    readonly physicalAddress?: string;
    readonly firmwareVersion?: string;
    readonly isVirtual: boolean;
    readonly virtualFormula?: string;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, orgId: string, regionId: string, branchId: string, buildingId: string, name: string, serialNumber: string, internalTag: string | null | undefined, meterType: z.infer<typeof MeterTypeSchema>, serviceType: z.infer<typeof MeterServiceTypeSchema> | null | undefined, unit: z.infer<typeof MeterUnitSchema> | null | undefined, accuracyClass: z.infer<typeof MeterAccuracyClassSchema> | null | undefined, multiplier: number | null | undefined, loggingIntervalMinutes: number | null | undefined, timeZone: string | null | undefined, isMain: boolean | null | undefined, isNetMetering: boolean | null | undefined, meterLevel: number, parentMeterId: string | null | undefined, assetId: string | null | undefined, status: z.infer<typeof MeterOperationalStatusSchema>, communicationStatus: z.infer<typeof MeterCommunicationStatusSchema> | null | undefined, lastCalibrationDate: string | null | undefined, nextCalibrationDate: string | null | undefined, monitorsPowerQuality: boolean | null | undefined, hasDataLogging: boolean | null | undefined, metrologicalSealNumber: string | null | undefined, protocol: z.infer<typeof MeterProtocolSchema>, physicalAddress: string | null | undefined, firmwareVersion: string | null | undefined, isVirtual: boolean | null | undefined, virtualFormula: string | null | undefined, tags: Record<string, string> | null | undefined, createdAt?: string, updatedAt?: string);
}
export type MeterDTOInput = z.infer<typeof MeterDTOSchema>;
export declare const parseMeterDTO: (input: unknown) => MeterDTO;
export declare const safeParseMeterDTO: (input: unknown) => z.SafeParseReturnType<{
    status: "INACTIVE" | "ACTIVE" | "FAULT";
    name: string;
    id: string;
    regionId: string;
    branchId: string;
    buildingId: string;
    serialNumber: string;
    orgId: string;
    meterType: "ELECTRICITY" | "GAS" | "WATER" | "THERMAL" | "BTU";
    meterLevel: number;
    protocol: "MQTT" | "MODBUS" | "BACNET" | "M_BUS" | "LORAWAN";
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    internalTag?: string | undefined;
    serviceType?: "UTILITY" | "SUBMETERING" | "GENERATION" | undefined;
    unit?: "BTU" | "KWH" | "M3" | "GJ" | "L" | undefined;
    accuracyClass?: "0.2S" | "0.5S" | "1.0" | "2.0" | undefined;
    multiplier?: number | undefined;
    loggingIntervalMinutes?: number | undefined;
    timeZone?: string | undefined;
    isMain?: boolean | undefined;
    isNetMetering?: boolean | undefined;
    parentMeterId?: string | undefined;
    assetId?: string | undefined;
    communicationStatus?: "DEGRADED" | "ONLINE" | "OFFLINE" | undefined;
    lastCalibrationDate?: string | undefined;
    nextCalibrationDate?: string | undefined;
    monitorsPowerQuality?: boolean | undefined;
    hasDataLogging?: boolean | undefined;
    metrologicalSealNumber?: string | undefined;
    physicalAddress?: string | undefined;
    firmwareVersion?: string | undefined;
    isVirtual?: boolean | undefined;
    virtualFormula?: string | undefined;
}, {
    status: "INACTIVE" | "ACTIVE" | "FAULT";
    name: string;
    id: string;
    regionId: string;
    tags: Record<string, string>;
    branchId: string;
    buildingId: string;
    serialNumber: string;
    orgId: string;
    meterType: "ELECTRICITY" | "GAS" | "WATER" | "THERMAL" | "BTU";
    serviceType: "UTILITY" | "SUBMETERING" | "GENERATION";
    unit: "BTU" | "KWH" | "M3" | "GJ" | "L";
    accuracyClass: "0.2S" | "0.5S" | "1.0" | "2.0";
    multiplier: number;
    loggingIntervalMinutes: number;
    timeZone: string;
    isMain: boolean;
    isNetMetering: boolean;
    meterLevel: number;
    communicationStatus: "DEGRADED" | "ONLINE" | "OFFLINE";
    monitorsPowerQuality: boolean;
    hasDataLogging: boolean;
    protocol: "MQTT" | "MODBUS" | "BACNET" | "M_BUS" | "LORAWAN";
    isVirtual: boolean;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    internalTag?: string | undefined;
    parentMeterId?: string | undefined;
    assetId?: string | undefined;
    lastCalibrationDate?: string | undefined;
    nextCalibrationDate?: string | undefined;
    metrologicalSealNumber?: string | undefined;
    physicalAddress?: string | undefined;
    firmwareVersion?: string | undefined;
    virtualFormula?: string | undefined;
}>;
//# sourceMappingURL=meter.dto.d.ts.map