import type { AssetType } from '@sms/common';
import type { AssetLifecycleStatus } from '@sms/common';
import { AssetDTO } from '@sms/common';
/** Activo energético anclado a Building + CostCenter. */
export declare class AssetEntity {
    readonly id: string;
    readonly organizationId: string;
    readonly regionId: string;
    readonly branchId: string;
    readonly buildingId: string;
    readonly costCenterId: string;
    readonly name: string;
    readonly assetTag?: string;
    readonly barcode?: string;
    readonly type: AssetType;
    readonly status: AssetLifecycleStatus;
    readonly criticality: 'LOW' | 'MEDIUM' | 'HIGH' | 'MISSION_CRITICAL';
    readonly manufacturer?: string;
    readonly model?: string;
    readonly serialNumber?: string;
    readonly installationDate: string;
    readonly usefulLifeYears: number;
    readonly decommissionDate?: string;
    readonly isSignificantEnergyUse: boolean;
    readonly nominalPowerKw: number;
    readonly standbyPowerKw?: number;
    readonly energySource: 'ELECTRICITY' | 'NATURAL_GAS' | 'DIESEL' | 'BIOMASS' | 'STEAM' | 'HYDROGEN';
    readonly nominalEfficiency: number;
    readonly dutyCycleExpected: number;
    readonly powerFactorTarget: number;
    readonly ghgScope: 'SCOPE_1' | 'SCOPE_2' | 'SCOPE_3';
    readonly emissionSourceCategory: 'STATIONARY_COMBUSTION' | 'FUGITIVE_EMISSIONS' | 'PROCESS_EMISSIONS';
    readonly fuelType?: string;
    readonly biogenicFraction: number;
    readonly refrigerantGasType?: string;
    readonly refrigerantChargeKg?: number;
    readonly refrigerantGWP?: number;
    readonly annualLeakageRateExpected: number;
    readonly meterId?: string;
    readonly cloudDeviceId?: string;
    readonly telemetryTopic?: string;
    readonly isVirtualAsset: boolean;
    readonly dataQualityScore: number;
    readonly lastMaintenanceDate?: string;
    readonly nextMaintenanceDate?: string;
    readonly maintenanceVendor?: string;
    readonly conditionIndex: 'NEW' | 'GOOD' | 'FAIR' | 'POOR';
    readonly efficiencyDegradationFactor: number;
    readonly redundancyLevel: 'N' | 'N+1' | '2N';
    readonly mtbfHours?: number;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, organizationId: string, regionId: string, branchId: string, buildingId: string, costCenterId: string, name: string, assetTag: string | undefined, barcode: string | undefined, type: AssetType, status: AssetLifecycleStatus, criticality: 'LOW' | 'MEDIUM' | 'HIGH' | 'MISSION_CRITICAL', manufacturer: string | undefined, model: string | undefined, serialNumber: string | undefined, installationDate: string, usefulLifeYears: number, decommissionDate: string | undefined, isSignificantEnergyUse: boolean, nominalPowerKw: number, standbyPowerKw: number | undefined, energySource: 'ELECTRICITY' | 'NATURAL_GAS' | 'DIESEL' | 'BIOMASS' | 'STEAM' | 'HYDROGEN', nominalEfficiency: number, dutyCycleExpected: number, powerFactorTarget: number, ghgScope: 'SCOPE_1' | 'SCOPE_2' | 'SCOPE_3', emissionSourceCategory: 'STATIONARY_COMBUSTION' | 'FUGITIVE_EMISSIONS' | 'PROCESS_EMISSIONS', fuelType: string | undefined, biogenicFraction: number, refrigerantGasType: string | undefined, refrigerantChargeKg: number | undefined, refrigerantGWP: number | undefined, annualLeakageRateExpected: number, meterId: string | undefined, cloudDeviceId: string | undefined, telemetryTopic: string | undefined, isVirtualAsset: boolean, dataQualityScore: number, lastMaintenanceDate: string | undefined, nextMaintenanceDate: string | undefined, maintenanceVendor: string | undefined, conditionIndex: 'NEW' | 'GOOD' | 'FAIR' | 'POOR', efficiencyDegradationFactor: number, redundancyLevel: 'N' | 'N+1' | '2N', mtbfHours: number | undefined, tags: Record<string, string>, createdAt?: string, updatedAt?: string);
    static fromDTO(dto: AssetDTO): AssetEntity;
    assertHierarchy(): void;
    assertUnderBuilding(expectedBuildingId: string): void;
    toValue(): AssetDTO;
}
//# sourceMappingURL=asset.entity.d.ts.map