import { z } from 'zod';
/**
 * Metadatos técnicos de la extracción IA/OCR (50+ campos) persistidos en `ia_extracted_data`
 * vía mapper (snake_case en DynamoDB, camelCase en TS).
 */
export declare const InvoiceIaTechnicalExtractionSchema: z.ZodObject<{
    extractionJobId: z.ZodDefault<z.ZodString>;
    extractionRunId: z.ZodDefault<z.ZodString>;
    pipelineVersion: z.ZodDefault<z.ZodString>;
    modelProvider: z.ZodDefault<z.ZodString>;
    modelName: z.ZodDefault<z.ZodString>;
    modelVersion: z.ZodDefault<z.ZodString>;
    promptTemplateId: z.ZodDefault<z.ZodString>;
    tokenizerEncoding: z.ZodDefault<z.ZodString>;
    inputTokenCount: z.ZodDefault<z.ZodNumber>;
    outputTokenCount: z.ZodDefault<z.ZodNumber>;
    totalLatencyMs: z.ZodDefault<z.ZodNumber>;
    queueWaitMs: z.ZodDefault<z.ZodNumber>;
    textractJobId: z.ZodDefault<z.ZodString>;
    textractApiVersion: z.ZodDefault<z.ZodString>;
    pageCount: z.ZodDefault<z.ZodNumber>;
    ocrMeanConfidence: z.ZodDefault<z.ZodNumber>;
    languageDetected: z.ZodDefault<z.ZodString>;
    documentHashSha256: z.ZodDefault<z.ZodString>;
    layoutEngineVersion: z.ZodDefault<z.ZodString>;
    tableRegionCount: z.ZodDefault<z.ZodNumber>;
    kvPairCount: z.ZodDefault<z.ZodNumber>;
    boundingBoxVersion: z.ZodDefault<z.ZodString>;
    dpiAssumed: z.ZodDefault<z.ZodNumber>;
    colorSpace: z.ZodDefault<z.ZodString>;
    pdfProducer: z.ZodDefault<z.ZodString>;
    pdfCreator: z.ZodDefault<z.ZodString>;
    encryptionDetected: z.ZodDefault<z.ZodBoolean>;
    digitalSignatureDetected: z.ZodDefault<z.ZodBoolean>;
    currencyGuess: z.ZodDefault<z.ZodString>;
    amountParseStrategy: z.ZodDefault<z.ZodString>;
    dateParseStrategy: z.ZodDefault<z.ZodString>;
    taxIdNormalizerVersion: z.ZodDefault<z.ZodString>;
    vendorFuzzyMatchScore: z.ZodDefault<z.ZodNumber>;
    climatiqRequestId: z.ZodDefault<z.ZodString>;
    climatiqActivityIdResolved: z.ZodDefault<z.ZodString>;
    gridRegionHint: z.ZodDefault<z.ZodString>;
    carbonIntensitySource: z.ZodDefault<z.ZodString>;
    dataQualityScore: z.ZodDefault<z.ZodNumber>;
    anomalyFlags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    redactionApplied: z.ZodDefault<z.ZodBoolean>;
    piiFieldsStripped: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    retryCount: z.ZodDefault<z.ZodNumber>;
    lastErrorCode: z.ZodDefault<z.ZodString>;
    lastErrorDetail: z.ZodDefault<z.ZodString>;
    workerHostId: z.ZodDefault<z.ZodString>;
    workerAz: z.ZodDefault<z.ZodString>;
    ingestionCorrelationId: z.ZodDefault<z.ZodString>;
    featureFlagsSnapshot: z.ZodDefault<z.ZodString>;
    schemaVersion: z.ZodDefault<z.ZodString>;
    /** Dimensión de embedding / vector store (trazabilidad de RAG). */
    embeddingVectorDimension: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    dataQualityScore: number;
    extractionJobId: string;
    extractionRunId: string;
    pipelineVersion: string;
    modelProvider: string;
    modelName: string;
    modelVersion: string;
    promptTemplateId: string;
    tokenizerEncoding: string;
    inputTokenCount: number;
    outputTokenCount: number;
    totalLatencyMs: number;
    queueWaitMs: number;
    textractJobId: string;
    textractApiVersion: string;
    pageCount: number;
    ocrMeanConfidence: number;
    languageDetected: string;
    documentHashSha256: string;
    layoutEngineVersion: string;
    tableRegionCount: number;
    kvPairCount: number;
    boundingBoxVersion: string;
    dpiAssumed: number;
    colorSpace: string;
    pdfProducer: string;
    pdfCreator: string;
    encryptionDetected: boolean;
    digitalSignatureDetected: boolean;
    currencyGuess: string;
    amountParseStrategy: string;
    dateParseStrategy: string;
    taxIdNormalizerVersion: string;
    vendorFuzzyMatchScore: number;
    climatiqRequestId: string;
    climatiqActivityIdResolved: string;
    gridRegionHint: string;
    carbonIntensitySource: string;
    anomalyFlags: string[];
    redactionApplied: boolean;
    piiFieldsStripped: string[];
    retryCount: number;
    lastErrorCode: string;
    lastErrorDetail: string;
    workerHostId: string;
    workerAz: string;
    ingestionCorrelationId: string;
    featureFlagsSnapshot: string;
    schemaVersion: string;
    embeddingVectorDimension: number;
}, {
    dataQualityScore?: number | undefined;
    extractionJobId?: string | undefined;
    extractionRunId?: string | undefined;
    pipelineVersion?: string | undefined;
    modelProvider?: string | undefined;
    modelName?: string | undefined;
    modelVersion?: string | undefined;
    promptTemplateId?: string | undefined;
    tokenizerEncoding?: string | undefined;
    inputTokenCount?: number | undefined;
    outputTokenCount?: number | undefined;
    totalLatencyMs?: number | undefined;
    queueWaitMs?: number | undefined;
    textractJobId?: string | undefined;
    textractApiVersion?: string | undefined;
    pageCount?: number | undefined;
    ocrMeanConfidence?: number | undefined;
    languageDetected?: string | undefined;
    documentHashSha256?: string | undefined;
    layoutEngineVersion?: string | undefined;
    tableRegionCount?: number | undefined;
    kvPairCount?: number | undefined;
    boundingBoxVersion?: string | undefined;
    dpiAssumed?: number | undefined;
    colorSpace?: string | undefined;
    pdfProducer?: string | undefined;
    pdfCreator?: string | undefined;
    encryptionDetected?: boolean | undefined;
    digitalSignatureDetected?: boolean | undefined;
    currencyGuess?: string | undefined;
    amountParseStrategy?: string | undefined;
    dateParseStrategy?: string | undefined;
    taxIdNormalizerVersion?: string | undefined;
    vendorFuzzyMatchScore?: number | undefined;
    climatiqRequestId?: string | undefined;
    climatiqActivityIdResolved?: string | undefined;
    gridRegionHint?: string | undefined;
    carbonIntensitySource?: string | undefined;
    anomalyFlags?: string[] | undefined;
    redactionApplied?: boolean | undefined;
    piiFieldsStripped?: string[] | undefined;
    retryCount?: number | undefined;
    lastErrorCode?: string | undefined;
    lastErrorDetail?: string | undefined;
    workerHostId?: string | undefined;
    workerAz?: string | undefined;
    ingestionCorrelationId?: string | undefined;
    featureFlagsSnapshot?: string | undefined;
    schemaVersion?: string | undefined;
    embeddingVectorDimension?: number | undefined;
}>;
export type InvoiceIaTechnicalExtraction = z.infer<typeof InvoiceIaTechnicalExtractionSchema>;
export declare const InvoiceIaExtractionSqsBodySchema: z.ZodObject<{
    tenantId: z.ZodString;
    orgId: z.ZodString;
    invoiceId: z.ZodString;
    pk: z.ZodString;
    sk: z.ZodString;
    extractionJobId: z.ZodOptional<z.ZodString>;
    rawModelOutputUri: z.ZodOptional<z.ZodString>;
    sourceBucket: z.ZodOptional<z.ZodString>;
    sourceKey: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    orgId: string;
    tenantId: string;
    invoiceId: string;
    pk: string;
    sk: string;
    extractionJobId?: string | undefined;
    rawModelOutputUri?: string | undefined;
    sourceBucket?: string | undefined;
    sourceKey?: string | undefined;
}, {
    orgId: string;
    tenantId: string;
    invoiceId: string;
    pk: string;
    sk: string;
    extractionJobId?: string | undefined;
    rawModelOutputUri?: string | undefined;
    sourceBucket?: string | undefined;
    sourceKey?: string | undefined;
}>;
export type InvoiceIaExtractionSqsBody = z.infer<typeof InvoiceIaExtractionSqsBodySchema>;
export declare function parseInvoiceIaExtractionSqsBody(input: unknown): InvoiceIaExtractionSqsBody;
/**
 * Inicializa el bloque técnico de IA con defaults deterministas (worker SQS).
 */
export declare function buildInitialInvoiceIaTechnicalExtraction(params: Partial<Pick<InvoiceIaTechnicalExtraction, 'extractionJobId' | 'workerHostId'>> & {
    readonly ingestionCorrelationId?: string;
}): InvoiceIaTechnicalExtraction;
//# sourceMappingURL=invoice-ia-technical-extraction.dto.d.ts.map