import { z } from 'zod';
export declare const InvoiceDTOSchema: z.ZodObject<{
    pk: z.ZodString;
    sk: z.ZodString;
    aiAnalysis: z.ZodObject<{
        activityId: z.ZodString;
        calculationMethod: z.ZodString;
        confidenceScore: z.ZodNumber;
        requiresReview: z.ZodBoolean;
        serviceType: z.ZodString;
        unit: z.ZodString;
        value: z.ZodNumber;
        year: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        value: number;
        serviceType: string;
        unit: string;
        activityId: string;
        calculationMethod: string;
        confidenceScore: number;
        requiresReview: boolean;
        year: number;
    }, {
        value: number;
        serviceType: string;
        unit: string;
        activityId: string;
        calculationMethod: string;
        confidenceScore: number;
        requiresReview: boolean;
        year: number;
    }>;
    analyticsDimensions: z.ZodObject<{
        assetId: z.ZodString;
        branchId: z.ZodString;
        periodMonth: z.ZodNumber;
        periodYear: z.ZodNumber;
        sector: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        branchId: string;
        assetId: string;
        periodMonth: number;
        periodYear: number;
        sector: string;
    }, {
        branchId: string;
        assetId: string;
        periodMonth: number;
        periodYear: number;
        sector: string;
    }>;
    climatiqResult: z.ZodObject<{
        co2e: z.ZodNumber;
        co2eUnit: z.ZodString;
        timestamp: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        co2e: number;
        co2eUnit: string;
        timestamp: string;
    }, {
        co2e: number;
        co2eUnit: string;
        timestamp: string;
    }>;
    extractedData: z.ZodObject<{
        billingPeriod: z.ZodObject<{
            start: z.ZodString;
            end: z.ZodString;
        }, "strip", z.ZodTypeAny, {
            start: string;
            end: string;
        }, {
            start: string;
            end: string;
        }>;
        invoiceDate: z.ZodString;
        invoiceNumber: z.ZodString;
        totalAmount: z.ZodNumber;
        vendor: z.ZodString;
        vendorTaxId: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        billingPeriod: {
            start: string;
            end: string;
        };
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: number;
        vendor: string;
        vendorTaxId: string;
    }, {
        billingPeriod: {
            start: string;
            end: string;
        };
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: number;
        vendor: string;
        vendorTaxId: string;
    }>;
    metadata: z.ZodObject<{
        s3Key: z.ZodString;
        status: z.ZodString;
        technicalHash: z.ZodString;
        uploadDate: z.ZodString;
        thoughtProcess: z.ZodObject<{
            detectedRawValues: z.ZodArray<z.ZodString, "many">;
            missingDataStrategy: z.ZodString;
            monetaryVsPhysicalCheck: z.ZodString;
        }, "strip", z.ZodTypeAny, {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        }, {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        }>;
    }, "strip", z.ZodTypeAny, {
        status: string;
        s3Key: string;
        technicalHash: string;
        uploadDate: string;
        thoughtProcess: {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        };
    }, {
        status: string;
        s3Key: string;
        technicalHash: string;
        uploadDate: string;
        thoughtProcess: {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        };
    }>;
    technicalExtraction: z.ZodDefault<z.ZodObject<{
        extractionJobId: z.ZodDefault<z.ZodString>;
        extractionRunId: z.ZodDefault<z.ZodString>;
        pipelineVersion: z.ZodDefault<z.ZodString>;
        modelProvider: z.ZodDefault<z.ZodString>;
        modelName: z.ZodDefault<z.ZodString>;
        modelVersion: z.ZodDefault<z.ZodString>;
        promptTemplateId: z.ZodDefault<z.ZodString>;
        tokenizerEncoding: z.ZodDefault<z.ZodString>;
        inputTokenCount: z.ZodDefault<z.ZodNumber>;
        outputTokenCount: z.ZodDefault<z.ZodNumber>;
        totalLatencyMs: z.ZodDefault<z.ZodNumber>;
        queueWaitMs: z.ZodDefault<z.ZodNumber>;
        textractJobId: z.ZodDefault<z.ZodString>;
        textractApiVersion: z.ZodDefault<z.ZodString>;
        pageCount: z.ZodDefault<z.ZodNumber>;
        ocrMeanConfidence: z.ZodDefault<z.ZodNumber>;
        languageDetected: z.ZodDefault<z.ZodString>;
        documentHashSha256: z.ZodDefault<z.ZodString>;
        layoutEngineVersion: z.ZodDefault<z.ZodString>;
        tableRegionCount: z.ZodDefault<z.ZodNumber>;
        kvPairCount: z.ZodDefault<z.ZodNumber>;
        boundingBoxVersion: z.ZodDefault<z.ZodString>;
        dpiAssumed: z.ZodDefault<z.ZodNumber>;
        colorSpace: z.ZodDefault<z.ZodString>;
        pdfProducer: z.ZodDefault<z.ZodString>;
        pdfCreator: z.ZodDefault<z.ZodString>;
        encryptionDetected: z.ZodDefault<z.ZodBoolean>;
        digitalSignatureDetected: z.ZodDefault<z.ZodBoolean>;
        currencyGuess: z.ZodDefault<z.ZodString>;
        amountParseStrategy: z.ZodDefault<z.ZodString>;
        dateParseStrategy: z.ZodDefault<z.ZodString>;
        taxIdNormalizerVersion: z.ZodDefault<z.ZodString>;
        vendorFuzzyMatchScore: z.ZodDefault<z.ZodNumber>;
        climatiqRequestId: z.ZodDefault<z.ZodString>;
        climatiqActivityIdResolved: z.ZodDefault<z.ZodString>;
        gridRegionHint: z.ZodDefault<z.ZodString>;
        carbonIntensitySource: z.ZodDefault<z.ZodString>;
        dataQualityScore: z.ZodDefault<z.ZodNumber>;
        anomalyFlags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        redactionApplied: z.ZodDefault<z.ZodBoolean>;
        piiFieldsStripped: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        retryCount: z.ZodDefault<z.ZodNumber>;
        lastErrorCode: z.ZodDefault<z.ZodString>;
        lastErrorDetail: z.ZodDefault<z.ZodString>;
        workerHostId: z.ZodDefault<z.ZodString>;
        workerAz: z.ZodDefault<z.ZodString>;
        ingestionCorrelationId: z.ZodDefault<z.ZodString>;
        featureFlagsSnapshot: z.ZodDefault<z.ZodString>;
        schemaVersion: z.ZodDefault<z.ZodString>;
        embeddingVectorDimension: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        dataQualityScore: number;
        extractionJobId: string;
        extractionRunId: string;
        pipelineVersion: string;
        modelProvider: string;
        modelName: string;
        modelVersion: string;
        promptTemplateId: string;
        tokenizerEncoding: string;
        inputTokenCount: number;
        outputTokenCount: number;
        totalLatencyMs: number;
        queueWaitMs: number;
        textractJobId: string;
        textractApiVersion: string;
        pageCount: number;
        ocrMeanConfidence: number;
        languageDetected: string;
        documentHashSha256: string;
        layoutEngineVersion: string;
        tableRegionCount: number;
        kvPairCount: number;
        boundingBoxVersion: string;
        dpiAssumed: number;
        colorSpace: string;
        pdfProducer: string;
        pdfCreator: string;
        encryptionDetected: boolean;
        digitalSignatureDetected: boolean;
        currencyGuess: string;
        amountParseStrategy: string;
        dateParseStrategy: string;
        taxIdNormalizerVersion: string;
        vendorFuzzyMatchScore: number;
        climatiqRequestId: string;
        climatiqActivityIdResolved: string;
        gridRegionHint: string;
        carbonIntensitySource: string;
        anomalyFlags: string[];
        redactionApplied: boolean;
        piiFieldsStripped: string[];
        retryCount: number;
        lastErrorCode: string;
        lastErrorDetail: string;
        workerHostId: string;
        workerAz: string;
        ingestionCorrelationId: string;
        featureFlagsSnapshot: string;
        schemaVersion: string;
        embeddingVectorDimension: number;
    }, {
        dataQualityScore?: number | undefined;
        extractionJobId?: string | undefined;
        extractionRunId?: string | undefined;
        pipelineVersion?: string | undefined;
        modelProvider?: string | undefined;
        modelName?: string | undefined;
        modelVersion?: string | undefined;
        promptTemplateId?: string | undefined;
        tokenizerEncoding?: string | undefined;
        inputTokenCount?: number | undefined;
        outputTokenCount?: number | undefined;
        totalLatencyMs?: number | undefined;
        queueWaitMs?: number | undefined;
        textractJobId?: string | undefined;
        textractApiVersion?: string | undefined;
        pageCount?: number | undefined;
        ocrMeanConfidence?: number | undefined;
        languageDetected?: string | undefined;
        documentHashSha256?: string | undefined;
        layoutEngineVersion?: string | undefined;
        tableRegionCount?: number | undefined;
        kvPairCount?: number | undefined;
        boundingBoxVersion?: string | undefined;
        dpiAssumed?: number | undefined;
        colorSpace?: string | undefined;
        pdfProducer?: string | undefined;
        pdfCreator?: string | undefined;
        encryptionDetected?: boolean | undefined;
        digitalSignatureDetected?: boolean | undefined;
        currencyGuess?: string | undefined;
        amountParseStrategy?: string | undefined;
        dateParseStrategy?: string | undefined;
        taxIdNormalizerVersion?: string | undefined;
        vendorFuzzyMatchScore?: number | undefined;
        climatiqRequestId?: string | undefined;
        climatiqActivityIdResolved?: string | undefined;
        gridRegionHint?: string | undefined;
        carbonIntensitySource?: string | undefined;
        anomalyFlags?: string[] | undefined;
        redactionApplied?: boolean | undefined;
        piiFieldsStripped?: string[] | undefined;
        retryCount?: number | undefined;
        lastErrorCode?: string | undefined;
        lastErrorDetail?: string | undefined;
        workerHostId?: string | undefined;
        workerAz?: string | undefined;
        ingestionCorrelationId?: string | undefined;
        featureFlagsSnapshot?: string | undefined;
        schemaVersion?: string | undefined;
        embeddingVectorDimension?: number | undefined;
    }>>;
    processedAt: z.ZodString;
    totalDaysProrated: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    pk: string;
    sk: string;
    aiAnalysis: {
        value: number;
        serviceType: string;
        unit: string;
        activityId: string;
        calculationMethod: string;
        confidenceScore: number;
        requiresReview: boolean;
        year: number;
    };
    analyticsDimensions: {
        branchId: string;
        assetId: string;
        periodMonth: number;
        periodYear: number;
        sector: string;
    };
    climatiqResult: {
        co2e: number;
        co2eUnit: string;
        timestamp: string;
    };
    extractedData: {
        billingPeriod: {
            start: string;
            end: string;
        };
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: number;
        vendor: string;
        vendorTaxId: string;
    };
    metadata: {
        status: string;
        s3Key: string;
        technicalHash: string;
        uploadDate: string;
        thoughtProcess: {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        };
    };
    technicalExtraction: {
        dataQualityScore: number;
        extractionJobId: string;
        extractionRunId: string;
        pipelineVersion: string;
        modelProvider: string;
        modelName: string;
        modelVersion: string;
        promptTemplateId: string;
        tokenizerEncoding: string;
        inputTokenCount: number;
        outputTokenCount: number;
        totalLatencyMs: number;
        queueWaitMs: number;
        textractJobId: string;
        textractApiVersion: string;
        pageCount: number;
        ocrMeanConfidence: number;
        languageDetected: string;
        documentHashSha256: string;
        layoutEngineVersion: string;
        tableRegionCount: number;
        kvPairCount: number;
        boundingBoxVersion: string;
        dpiAssumed: number;
        colorSpace: string;
        pdfProducer: string;
        pdfCreator: string;
        encryptionDetected: boolean;
        digitalSignatureDetected: boolean;
        currencyGuess: string;
        amountParseStrategy: string;
        dateParseStrategy: string;
        taxIdNormalizerVersion: string;
        vendorFuzzyMatchScore: number;
        climatiqRequestId: string;
        climatiqActivityIdResolved: string;
        gridRegionHint: string;
        carbonIntensitySource: string;
        anomalyFlags: string[];
        redactionApplied: boolean;
        piiFieldsStripped: string[];
        retryCount: number;
        lastErrorCode: string;
        lastErrorDetail: string;
        workerHostId: string;
        workerAz: string;
        ingestionCorrelationId: string;
        featureFlagsSnapshot: string;
        schemaVersion: string;
        embeddingVectorDimension: number;
    };
    processedAt: string;
    totalDaysProrated: number;
}, {
    pk: string;
    sk: string;
    aiAnalysis: {
        value: number;
        serviceType: string;
        unit: string;
        activityId: string;
        calculationMethod: string;
        confidenceScore: number;
        requiresReview: boolean;
        year: number;
    };
    analyticsDimensions: {
        branchId: string;
        assetId: string;
        periodMonth: number;
        periodYear: number;
        sector: string;
    };
    climatiqResult: {
        co2e: number;
        co2eUnit: string;
        timestamp: string;
    };
    extractedData: {
        billingPeriod: {
            start: string;
            end: string;
        };
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: number;
        vendor: string;
        vendorTaxId: string;
    };
    metadata: {
        status: string;
        s3Key: string;
        technicalHash: string;
        uploadDate: string;
        thoughtProcess: {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        };
    };
    processedAt: string;
    totalDaysProrated: number;
    technicalExtraction?: {
        dataQualityScore?: number | undefined;
        extractionJobId?: string | undefined;
        extractionRunId?: string | undefined;
        pipelineVersion?: string | undefined;
        modelProvider?: string | undefined;
        modelName?: string | undefined;
        modelVersion?: string | undefined;
        promptTemplateId?: string | undefined;
        tokenizerEncoding?: string | undefined;
        inputTokenCount?: number | undefined;
        outputTokenCount?: number | undefined;
        totalLatencyMs?: number | undefined;
        queueWaitMs?: number | undefined;
        textractJobId?: string | undefined;
        textractApiVersion?: string | undefined;
        pageCount?: number | undefined;
        ocrMeanConfidence?: number | undefined;
        languageDetected?: string | undefined;
        documentHashSha256?: string | undefined;
        layoutEngineVersion?: string | undefined;
        tableRegionCount?: number | undefined;
        kvPairCount?: number | undefined;
        boundingBoxVersion?: string | undefined;
        dpiAssumed?: number | undefined;
        colorSpace?: string | undefined;
        pdfProducer?: string | undefined;
        pdfCreator?: string | undefined;
        encryptionDetected?: boolean | undefined;
        digitalSignatureDetected?: boolean | undefined;
        currencyGuess?: string | undefined;
        amountParseStrategy?: string | undefined;
        dateParseStrategy?: string | undefined;
        taxIdNormalizerVersion?: string | undefined;
        vendorFuzzyMatchScore?: number | undefined;
        climatiqRequestId?: string | undefined;
        climatiqActivityIdResolved?: string | undefined;
        gridRegionHint?: string | undefined;
        carbonIntensitySource?: string | undefined;
        anomalyFlags?: string[] | undefined;
        redactionApplied?: boolean | undefined;
        piiFieldsStripped?: string[] | undefined;
        retryCount?: number | undefined;
        lastErrorCode?: string | undefined;
        lastErrorDetail?: string | undefined;
        workerHostId?: string | undefined;
        workerAz?: string | undefined;
        ingestionCorrelationId?: string | undefined;
        featureFlagsSnapshot?: string | undefined;
        schemaVersion?: string | undefined;
        embeddingVectorDimension?: number | undefined;
    } | undefined;
}>;
export type InvoiceDTO = z.infer<typeof InvoiceDTOSchema>;
export declare const parseInvoiceDTO: (input: unknown) => InvoiceDTO;
export declare const safeParseInvoiceDTO: (input: unknown) => z.SafeParseReturnType<{
    pk: string;
    sk: string;
    aiAnalysis: {
        value: number;
        serviceType: string;
        unit: string;
        activityId: string;
        calculationMethod: string;
        confidenceScore: number;
        requiresReview: boolean;
        year: number;
    };
    analyticsDimensions: {
        branchId: string;
        assetId: string;
        periodMonth: number;
        periodYear: number;
        sector: string;
    };
    climatiqResult: {
        co2e: number;
        co2eUnit: string;
        timestamp: string;
    };
    extractedData: {
        billingPeriod: {
            start: string;
            end: string;
        };
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: number;
        vendor: string;
        vendorTaxId: string;
    };
    metadata: {
        status: string;
        s3Key: string;
        technicalHash: string;
        uploadDate: string;
        thoughtProcess: {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        };
    };
    processedAt: string;
    totalDaysProrated: number;
    technicalExtraction?: {
        dataQualityScore?: number | undefined;
        extractionJobId?: string | undefined;
        extractionRunId?: string | undefined;
        pipelineVersion?: string | undefined;
        modelProvider?: string | undefined;
        modelName?: string | undefined;
        modelVersion?: string | undefined;
        promptTemplateId?: string | undefined;
        tokenizerEncoding?: string | undefined;
        inputTokenCount?: number | undefined;
        outputTokenCount?: number | undefined;
        totalLatencyMs?: number | undefined;
        queueWaitMs?: number | undefined;
        textractJobId?: string | undefined;
        textractApiVersion?: string | undefined;
        pageCount?: number | undefined;
        ocrMeanConfidence?: number | undefined;
        languageDetected?: string | undefined;
        documentHashSha256?: string | undefined;
        layoutEngineVersion?: string | undefined;
        tableRegionCount?: number | undefined;
        kvPairCount?: number | undefined;
        boundingBoxVersion?: string | undefined;
        dpiAssumed?: number | undefined;
        colorSpace?: string | undefined;
        pdfProducer?: string | undefined;
        pdfCreator?: string | undefined;
        encryptionDetected?: boolean | undefined;
        digitalSignatureDetected?: boolean | undefined;
        currencyGuess?: string | undefined;
        amountParseStrategy?: string | undefined;
        dateParseStrategy?: string | undefined;
        taxIdNormalizerVersion?: string | undefined;
        vendorFuzzyMatchScore?: number | undefined;
        climatiqRequestId?: string | undefined;
        climatiqActivityIdResolved?: string | undefined;
        gridRegionHint?: string | undefined;
        carbonIntensitySource?: string | undefined;
        anomalyFlags?: string[] | undefined;
        redactionApplied?: boolean | undefined;
        piiFieldsStripped?: string[] | undefined;
        retryCount?: number | undefined;
        lastErrorCode?: string | undefined;
        lastErrorDetail?: string | undefined;
        workerHostId?: string | undefined;
        workerAz?: string | undefined;
        ingestionCorrelationId?: string | undefined;
        featureFlagsSnapshot?: string | undefined;
        schemaVersion?: string | undefined;
        embeddingVectorDimension?: number | undefined;
    } | undefined;
}, {
    pk: string;
    sk: string;
    aiAnalysis: {
        value: number;
        serviceType: string;
        unit: string;
        activityId: string;
        calculationMethod: string;
        confidenceScore: number;
        requiresReview: boolean;
        year: number;
    };
    analyticsDimensions: {
        branchId: string;
        assetId: string;
        periodMonth: number;
        periodYear: number;
        sector: string;
    };
    climatiqResult: {
        co2e: number;
        co2eUnit: string;
        timestamp: string;
    };
    extractedData: {
        billingPeriod: {
            start: string;
            end: string;
        };
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: number;
        vendor: string;
        vendorTaxId: string;
    };
    metadata: {
        status: string;
        s3Key: string;
        technicalHash: string;
        uploadDate: string;
        thoughtProcess: {
            detectedRawValues: string[];
            missingDataStrategy: string;
            monetaryVsPhysicalCheck: string;
        };
    };
    technicalExtraction: {
        dataQualityScore: number;
        extractionJobId: string;
        extractionRunId: string;
        pipelineVersion: string;
        modelProvider: string;
        modelName: string;
        modelVersion: string;
        promptTemplateId: string;
        tokenizerEncoding: string;
        inputTokenCount: number;
        outputTokenCount: number;
        totalLatencyMs: number;
        queueWaitMs: number;
        textractJobId: string;
        textractApiVersion: string;
        pageCount: number;
        ocrMeanConfidence: number;
        languageDetected: string;
        documentHashSha256: string;
        layoutEngineVersion: string;
        tableRegionCount: number;
        kvPairCount: number;
        boundingBoxVersion: string;
        dpiAssumed: number;
        colorSpace: string;
        pdfProducer: string;
        pdfCreator: string;
        encryptionDetected: boolean;
        digitalSignatureDetected: boolean;
        currencyGuess: string;
        amountParseStrategy: string;
        dateParseStrategy: string;
        taxIdNormalizerVersion: string;
        vendorFuzzyMatchScore: number;
        climatiqRequestId: string;
        climatiqActivityIdResolved: string;
        gridRegionHint: string;
        carbonIntensitySource: string;
        anomalyFlags: string[];
        redactionApplied: boolean;
        piiFieldsStripped: string[];
        retryCount: number;
        lastErrorCode: string;
        lastErrorDetail: string;
        workerHostId: string;
        workerAz: string;
        ingestionCorrelationId: string;
        featureFlagsSnapshot: string;
        schemaVersion: string;
        embeddingVectorDimension: number;
    };
    processedAt: string;
    totalDaysProrated: number;
}>;
//# sourceMappingURL=invoice.dto.d.ts.map