/** common Zod contracts and DTOs (`@sms/common`, carpeta `libs/common` → `dtos/` + `schemas/`) — consumible por Angular y Node. */
export { EntityType, EntityTypeSchema, ENTITY_TYPE_VALUES, isEntityType, ENTITY_TYPE_I18N, getEntityTypeI18nKey, ENERGY_SERVICE_TYPE_I18N, getEnergyServiceTypeI18nKey } from './dtos/common/i18n/index.js';
export { SmsIdSchema } from './schemas/sms-id.schema.js';
export { AssetTypeSchema, MeterTypeSchema, UserRoleSchema, ASSET_TYPE_TO_PERSISTENCE, METER_TYPE_TO_PERSISTENCE } from './dtos/shared/domain-enums.js';
export { SmsDomainError, RegionDomainError } from './dtos/common/sms-domain-error.js';
export { AddressDTOSchema } from './dtos/common/address.dto.js';
export { GeoCoordinatesDTOSchema } from './dtos/common/geo.dto.js';
export { ROLE_TO_CODE, decodeAssetType, decodeMeterType, decodeRole } from './dtos/common/persistence-codecs.js';
export { RegionDTOSchema, RegionalManagerDTOSchema, ClimateZoneSchema, CarbonMarketTypeSchema, MaturityLevelSchema, EconomicAreaSchema, parseRegionDTO, safeParseRegionDTO, RegionDTO } from './dtos/region/index.js';
export { BranchDTOSchema, BranchStatusSchema, BranchTypeSchema, OwnershipTypeSchema, BackupPowerTypeSchema, OperatingHoursDTOSchema, BranchManagerDTOSchema, parseBranchDTO, safeParseBranchDTO, BranchDTO } from './dtos/branch/index.js';
export { BuildingDTOSchema, parseBuildingDTO, safeParseBuildingDTO, BuildingDTO, BuildingInsulationQualitySchema, BuildingRoofTypeSchema, BuildingMaintenanceStatusSchema, BuildingLightingTechnologySchema, BuildingDataGranularitySchema, BuildingSubmeteringTopologySchema } from './dtos/building/index.js';
export { CostCenterDTOSchema, parseCostCenterDTO, safeParseCostCenterDTO, CostCenterDTO, CostCenterTypeSchema, CostCenterForecastModelSchema } from './dtos/cost-center/index.js';
export { AssetDTOSchema, parseAssetDTO, safeParseAssetDTO, AssetDTO, AssetCriticalitySchema, AssetEnergySourceSchema, AssetGhgScopeSchema, AssetEmissionSourceCategorySchema, AssetConditionIndexSchema, AssetRedundancyLevelSchema } from './dtos/asset/index.js';
export { MeterDTOSchema, parseMeterDTO, safeParseMeterDTO, MeterDTO, MeterServiceTypeSchema, MeterUnitSchema, MeterAccuracyClassSchema, MeterCommunicationStatusSchema } from './dtos/meter/index.js';
export { UserDTOSchema, parseUserDTO, safeParseUserDTO } from './dtos/user/index.js';
export { InvoiceDTOSchema, parseInvoiceDTO, safeParseInvoiceDTO, InvoiceProcessingSkeletonSchema, buildInvoiceProcessingSkeleton, InvoiceLifecycleStatusSchema, InvoiceCalculationMethodSchema, InvoiceBillingPeriodSchema, InvoiceExtractedDataSchema, InvoiceThoughtProcessSchema, InvoiceAiAnalysisSchema, InvoiceAnalyticsDimensionsSchema, InvoiceClimatiqResultSchema, InvoiceMetadataSchema, InvoiceDdbItemSchema, InvoiceConfirmPayloadSchema, parseInvoiceDdbItem, safeParseInvoiceDdbItem, parseInvoiceConfirmPayload, safeParseInvoiceConfirmPayload, InvoiceAuditActorSchema, InvoiceAuditActionSchema, InvoiceAuditSourceSchema, InvoiceAuditEntrySchema, InvoiceAuditTrailSchema, buildInitialAuditEntry, InvoiceIaTechnicalExtractionSchema, InvoiceIaExtractionSqsBodySchema, parseInvoiceIaExtractionSqsBody, buildInitialInvoiceIaTechnicalExtraction } from './dtos/invoice/index.js';
export { PresignedUploadUrlInputSchema, parsePresignedUploadUrlInput, safeParsePresignedUploadUrlInput } from './dtos/presigned-upload/index.js';
export { IndustrySectorSchema, CurrencyCodeSchema, ReportingCurrencyCodeSchema, SubscriptionPlanSchema, FacilityTypeSchema, IanaTimezoneSchema, BuildingUsageTypeSchema, OperationalStatusSchema, HvacTypeSchema, CostAllocationMethodSchema, UserLanguageSchema, EnergyServiceTypeSchema, TariffPricingModelSchema, ProductionUnitTypeSchema, ProductionShiftModeSchema, MeterProtocolSchema, LifecycleStatusSchema, AssetLifecycleStatusSchema, MeterOperationalStatusSchema, TariffLifecycleStatusSchema, MainFuelTypeSchema } from './dtos/shared/graphql-setup-enums.js';  
export { OrgConfigDTOSchema, parseOrgConfigDTO, safeParseOrgConfigDTO, OrganizationDTOSchema, parseOrganizationDTO, safeParseOrganizationDTO, OrganizationDTO } from './dtos/org-config/index.js';
export { AlertRuleDTOSchema, parseAlertRuleDTO, safeParseAlertRuleDTO, AlertRuleDTO, generateAlertRuleId, AlertRuleEntityTypeSchema, AlertRuleDetectionTypeSchema, AlertRuleThresholdOperatorSymbolSchema, AlertRuleAggregationMethodSchema, AlertRulePrioritySchema, AlertRuleRuleStatusSchema, AlertRuleMonitorScopeSchema, AlertRuleNotificationChannelSchema } from './dtos/alert-rule/index.js';
export { TariffDTOSchema, parseTariffDTO, safeParseTariffDTO, TariffDTO, TariffDemandChargeUnitSchema, TariffSeasonSchema, TariffTierRatePairSchema, generateTariffId } from './dtos/tariff/index.js';
export { ProductionLogDTOSchema, parseProductionLogDTO, safeParseProductionLogDTO } from './dtos/production-log/index.js';
export { EmissionFactorDTOSchema, parseEmissionFactorDTO, safeParseEmissionFactorDTO, EmissionFactorDTO, generateEmissionFactorId, EmissionFactorActivityTypeSchema, EmissionFactorScopeNumberSchema, EmissionFactorPhysicalUnitSchema, EmissionFactorCalculationMethodSchema, EmissionFactorGwpReferenceSchema, EmissionFactorCatalogStatusSchema, EmissionFactorDataQualityTierSchema } from './dtos/emission-factor/index.js';
export { InvoiceSkSchema, S3DispatcherInvokeSchema, parseS3DispatcherInvoke, safeParseS3DispatcherInvoke, DecodedInvoiceUploadKeySchema, safeParseDecodedInvoiceUploadKey, InvoiceDispatchQueueMessageSchema, parseInvoiceDispatchQueueMessage, safeParseInvoiceDispatchQueueMessage, DispatcherEnqueueResultSchema, parseDispatcherEnqueueResult, InvoiceWorkerLegacyQueueBodySchema, parseInvoiceWorkerPipelineInput } from './dtos/s3-invoice-dispatch/index.js';
//# sourceMappingURL=index.js.map