import { z } from 'zod';
import { EnergyServiceTypeSchema, TariffLifecycleStatusSchema, TariffPricingModelSchema } from '../common/graphql-setup-enums.js';
export declare const TariffDemandChargeUnitSchema: z.ZodEnum<["KW", "KVA"]>;
export declare const TariffSeasonSchema: z.ZodEnum<["SUMMER", "WINTER", "TRANSITION", "ALL_YEAR"]>;
export type TariffDemandChargeUnit = z.infer<typeof TariffDemandChargeUnitSchema>;
export type TariffSeason = z.infer<typeof TariffSeasonSchema>;
export declare const TariffTierRatePairSchema: z.ZodObject<{
    limit: z.ZodNumber;
    rate: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    limit: number;
    rate: number;
}, {
    limit: number;
    rate: number;
}>;
/** Genera id estable para mutaciones sin `id` en el input. */
export declare function generateTariffId(): string;
export declare const TariffDTOSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    orgId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    branchId: z.ZodUnion<[z.ZodString, z.ZodString]>;
    buildingId: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    serviceType: z.ZodEnum<["ELECTRICITY", "GAS", "WATER", "STEAM"]>;
    providerName: z.ZodString;
    contractId: z.ZodString;
    pricingModel: z.ZodEnum<["FIXED", "TIME_OF_USE", "TIERED", "INDEXED"]>;
    currency: z.ZodDefault<z.ZodString>;
    baseRate: z.ZodNumber;
    expectedAverageRate: z.ZodOptional<z.ZodNumber>;
    demandChargeRate: z.ZodOptional<z.ZodNumber>;
    demandChargeUnit: z.ZodDefault<z.ZodEnum<["KW", "KVA"]>>;
    fixedMonthlyFee: z.ZodOptional<z.ZodNumber>;
    taxPercentage: z.ZodDefault<z.ZodNumber>;
    touScheduleId: z.ZodOptional<z.ZodString>;
    peakRate: z.ZodOptional<z.ZodNumber>;
    valleyRate: z.ZodOptional<z.ZodNumber>;
    shoulderRate: z.ZodOptional<z.ZodNumber>;
    season: z.ZodDefault<z.ZodEnum<["SUMMER", "WINTER", "TRANSITION", "ALL_YEAR"]>>;
    tieredRates: z.ZodOptional<z.ZodArray<z.ZodObject<{
        limit: z.ZodNumber;
        rate: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        limit: number;
        rate: number;
    }, {
        limit: number;
        rate: number;
    }>, "many">>;
    fuelAdjustmentFactor: z.ZodDefault<z.ZodNumber>;
    indexReferenceId: z.ZodOptional<z.ZodString>;
    indexAdjustmentFormula: z.ZodOptional<z.ZodString>;
    volatilityIndex: z.ZodDefault<z.ZodNumber>;
    reactiveEnergyCharge: z.ZodOptional<z.ZodNumber>;
    powerFactorThreshold: z.ZodDefault<z.ZodNumber>;
    greenPremium: z.ZodDefault<z.ZodNumber>;
    carbonTaxRate: z.ZodOptional<z.ZodNumber>;
    efficiencyRebateRate: z.ZodOptional<z.ZodNumber>;
    validFrom: z.ZodString;
    validTo: z.ZodString;
    billingCycleDay: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["ACTIVE", "EXPIRED", "PENDING", "ARCHIVED"]>>;
    tags: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "ACTIVE" | "EXPIRED" | "PENDING" | "ARCHIVED";
    tags: Record<string, string>;
    branchId: string;
    currency: string;
    orgId: string;
    serviceType: "ELECTRICITY" | "GAS" | "WATER" | "STEAM";
    providerName: string;
    contractId: string;
    pricingModel: "FIXED" | "TIME_OF_USE" | "TIERED" | "INDEXED";
    baseRate: number;
    demandChargeUnit: "KW" | "KVA";
    taxPercentage: number;
    season: "SUMMER" | "WINTER" | "TRANSITION" | "ALL_YEAR";
    fuelAdjustmentFactor: number;
    volatilityIndex: number;
    powerFactorThreshold: number;
    greenPremium: number;
    validFrom: string;
    validTo: string;
    billingCycleDay: number;
    id?: string | undefined;
    carbonTaxRate?: number | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    buildingId?: string | undefined;
    expectedAverageRate?: number | undefined;
    demandChargeRate?: number | undefined;
    fixedMonthlyFee?: number | undefined;
    touScheduleId?: string | undefined;
    peakRate?: number | undefined;
    valleyRate?: number | undefined;
    shoulderRate?: number | undefined;
    tieredRates?: {
        limit: number;
        rate: number;
    }[] | undefined;
    indexReferenceId?: string | undefined;
    indexAdjustmentFormula?: string | undefined;
    reactiveEnergyCharge?: number | undefined;
    efficiencyRebateRate?: number | undefined;
}, {
    branchId: string;
    orgId: string;
    serviceType: "ELECTRICITY" | "GAS" | "WATER" | "STEAM";
    providerName: string;
    contractId: string;
    pricingModel: "FIXED" | "TIME_OF_USE" | "TIERED" | "INDEXED";
    baseRate: number;
    validFrom: string;
    validTo: string;
    status?: "ACTIVE" | "EXPIRED" | "PENDING" | "ARCHIVED" | undefined;
    id?: string | undefined;
    carbonTaxRate?: number | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    buildingId?: string | undefined;
    currency?: string | undefined;
    expectedAverageRate?: number | undefined;
    demandChargeRate?: number | undefined;
    demandChargeUnit?: "KW" | "KVA" | undefined;
    fixedMonthlyFee?: number | undefined;
    taxPercentage?: number | undefined;
    touScheduleId?: string | undefined;
    peakRate?: number | undefined;
    valleyRate?: number | undefined;
    shoulderRate?: number | undefined;
    season?: "SUMMER" | "WINTER" | "TRANSITION" | "ALL_YEAR" | undefined;
    tieredRates?: {
        limit: number;
        rate: number;
    }[] | undefined;
    fuelAdjustmentFactor?: number | undefined;
    indexReferenceId?: string | undefined;
    indexAdjustmentFormula?: string | undefined;
    volatilityIndex?: number | undefined;
    reactiveEnergyCharge?: number | undefined;
    powerFactorThreshold?: number | undefined;
    greenPremium?: number | undefined;
    efficiencyRebateRate?: number | undefined;
    billingCycleDay?: number | undefined;
}>;
export type TariffDTOInput = z.infer<typeof TariffDTOSchema>;
export type TariffTierRatePair = z.infer<typeof TariffTierRatePairSchema>;
export declare class TariffDTO {
    readonly id: string;
    readonly orgId: string;
    readonly branchId: string;
    readonly buildingId?: string;
    readonly serviceType: z.infer<typeof EnergyServiceTypeSchema>;
    readonly providerName: string;
    readonly contractId: string;
    readonly pricingModel: z.infer<typeof TariffPricingModelSchema>;
    readonly currency: string;
    readonly baseRate: number;
    readonly expectedAverageRate?: number;
    readonly demandChargeRate?: number;
    readonly demandChargeUnit: z.infer<typeof TariffDemandChargeUnitSchema>;
    readonly fixedMonthlyFee?: number;
    readonly taxPercentage: number;
    readonly touScheduleId?: string;
    readonly peakRate?: number;
    readonly valleyRate?: number;
    readonly shoulderRate?: number;
    readonly season: z.infer<typeof TariffSeasonSchema>;
    readonly tieredRates?: TariffTierRatePair[];
    readonly fuelAdjustmentFactor: number;
    readonly indexReferenceId?: string;
    readonly indexAdjustmentFormula?: string;
    readonly volatilityIndex: number;
    readonly reactiveEnergyCharge?: number;
    readonly powerFactorThreshold: number;
    readonly greenPremium: number;
    readonly carbonTaxRate?: number;
    readonly efficiencyRebateRate?: number;
    readonly validFrom: string;
    readonly validTo: string;
    readonly billingCycleDay: number;
    readonly status: z.infer<typeof TariffLifecycleStatusSchema>;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, orgId: string, branchId: string, buildingId: string | null | undefined, serviceType: z.infer<typeof EnergyServiceTypeSchema>, providerName: string, contractId: string, pricingModel: z.infer<typeof TariffPricingModelSchema>, currency: string | null | undefined, baseRate: number, expectedAverageRate: number | null | undefined, demandChargeRate: number | null | undefined, demandChargeUnit: z.infer<typeof TariffDemandChargeUnitSchema> | null | undefined, fixedMonthlyFee: number | null | undefined, taxPercentage: number | null | undefined, touScheduleId: string | null | undefined, peakRate: number | null | undefined, valleyRate: number | null | undefined, shoulderRate: number | null | undefined, season: z.infer<typeof TariffSeasonSchema> | null | undefined, tieredRates: TariffTierRatePair[] | null | undefined, fuelAdjustmentFactor: number | null | undefined, indexReferenceId: string | null | undefined, indexAdjustmentFormula: string | null | undefined, volatilityIndex: number | null | undefined, reactiveEnergyCharge: number | null | undefined, powerFactorThreshold: number | null | undefined, greenPremium: number | null | undefined, carbonTaxRate: number | null | undefined, efficiencyRebateRate: number | null | undefined, validFrom: string, validTo: string, billingCycleDay: number | null | undefined, status: z.infer<typeof TariffLifecycleStatusSchema>, tags: Record<string, string> | null | undefined, createdAt?: string, updatedAt?: string);
}
export declare const parseTariffDTO: (input: unknown) => TariffDTO;
export declare const safeParseTariffDTO: (input: unknown) => z.SafeParseReturnType<{
    branchId: string;
    orgId: string;
    serviceType: "ELECTRICITY" | "GAS" | "WATER" | "STEAM";
    providerName: string;
    contractId: string;
    pricingModel: "FIXED" | "TIME_OF_USE" | "TIERED" | "INDEXED";
    baseRate: number;
    validFrom: string;
    validTo: string;
    status?: "ACTIVE" | "EXPIRED" | "PENDING" | "ARCHIVED" | undefined;
    id?: string | undefined;
    carbonTaxRate?: number | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    buildingId?: string | undefined;
    currency?: string | undefined;
    expectedAverageRate?: number | undefined;
    demandChargeRate?: number | undefined;
    demandChargeUnit?: "KW" | "KVA" | undefined;
    fixedMonthlyFee?: number | undefined;
    taxPercentage?: number | undefined;
    touScheduleId?: string | undefined;
    peakRate?: number | undefined;
    valleyRate?: number | undefined;
    shoulderRate?: number | undefined;
    season?: "SUMMER" | "WINTER" | "TRANSITION" | "ALL_YEAR" | undefined;
    tieredRates?: {
        limit: number;
        rate: number;
    }[] | undefined;
    fuelAdjustmentFactor?: number | undefined;
    indexReferenceId?: string | undefined;
    indexAdjustmentFormula?: string | undefined;
    volatilityIndex?: number | undefined;
    reactiveEnergyCharge?: number | undefined;
    powerFactorThreshold?: number | undefined;
    greenPremium?: number | undefined;
    efficiencyRebateRate?: number | undefined;
    billingCycleDay?: number | undefined;
}, {
    status: "ACTIVE" | "EXPIRED" | "PENDING" | "ARCHIVED";
    tags: Record<string, string>;
    branchId: string;
    currency: string;
    orgId: string;
    serviceType: "ELECTRICITY" | "GAS" | "WATER" | "STEAM";
    providerName: string;
    contractId: string;
    pricingModel: "FIXED" | "TIME_OF_USE" | "TIERED" | "INDEXED";
    baseRate: number;
    demandChargeUnit: "KW" | "KVA";
    taxPercentage: number;
    season: "SUMMER" | "WINTER" | "TRANSITION" | "ALL_YEAR";
    fuelAdjustmentFactor: number;
    volatilityIndex: number;
    powerFactorThreshold: number;
    greenPremium: number;
    validFrom: string;
    validTo: string;
    billingCycleDay: number;
    id?: string | undefined;
    carbonTaxRate?: number | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    buildingId?: string | undefined;
    expectedAverageRate?: number | undefined;
    demandChargeRate?: number | undefined;
    fixedMonthlyFee?: number | undefined;
    touScheduleId?: string | undefined;
    peakRate?: number | undefined;
    valleyRate?: number | undefined;
    shoulderRate?: number | undefined;
    tieredRates?: {
        limit: number;
        rate: number;
    }[] | undefined;
    indexReferenceId?: string | undefined;
    indexAdjustmentFormula?: string | undefined;
    reactiveEnergyCharge?: number | undefined;
    efficiencyRebateRate?: number | undefined;
}>;
//# sourceMappingURL=tariff.dto.d.ts.map