import { z } from 'zod';
export declare const EmissionFactorActivityTypeSchema: z.ZodEnum<["ELECTRICITY", "NATURAL_GAS", "DIESEL", "FLIGHT", "REFRIGERANT", "WASTE", "LOGISTICS"]>;
export declare const EmissionFactorScopeNumberSchema: z.ZodUnion<[z.ZodLiteral<1>, z.ZodLiteral<2>, z.ZodLiteral<3>]>;
export declare const EmissionFactorPhysicalUnitSchema: z.ZodEnum<["KWH", "M3", "KG", "L", "TON_KM", "TJ", "PASSENGER_KM"]>;
export declare const EmissionFactorCalculationMethodSchema: z.ZodEnum<["LOCATION_BASED", "MARKET_BASED"]>;
export declare const EmissionFactorGwpReferenceSchema: z.ZodEnum<["AR4", "AR5", "AR6"]>;
export declare const EmissionFactorCatalogStatusSchema: z.ZodEnum<["DRAFT", "ACTIVE", "DEPRECATED", "ARCHIVED"]>;
export declare const EmissionFactorDataQualityTierSchema: z.ZodUnion<[z.ZodLiteral<1>, z.ZodLiteral<2>, z.ZodLiteral<3>, z.ZodLiteral<4>, z.ZodLiteral<5>]>;
export declare function generateEmissionFactorId(): string;
export declare const EmissionFactorDTOSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    name: z.ZodString;
    year: z.ZodNumber;
    regionCode: z.ZodString;
    activityType: z.ZodEffects<z.ZodEnum<["ELECTRICITY", "NATURAL_GAS", "DIESEL", "FLIGHT", "REFRIGERANT", "WASTE", "LOGISTICS"]>, "ELECTRICITY" | "DIESEL" | "LOGISTICS" | "NATURAL_GAS" | "FLIGHT" | "REFRIGERANT" | "WASTE", unknown>;
    scope: z.ZodEffects<z.ZodUnion<[z.ZodLiteral<1>, z.ZodLiteral<2>, z.ZodLiteral<3>]>, 1 | 3 | 2, unknown>;
    calculationMethod: z.ZodEffects<z.ZodOptional<z.ZodEnum<["LOCATION_BASED", "MARKET_BASED"]>>, "LOCATION_BASED" | "MARKET_BASED" | undefined, unknown>;
    unit: z.ZodEffects<z.ZodEnum<["KWH", "M3", "KG", "L", "TON_KM", "TJ", "PASSENGER_KM"]>, "KWH" | "M3" | "L" | "KG" | "TON_KM" | "TJ" | "PASSENGER_KM", unknown>;
    value: z.ZodNumber;
    co2Value: z.ZodOptional<z.ZodNumber>;
    ch4Value: z.ZodOptional<z.ZodNumber>;
    n2oValue: z.ZodOptional<z.ZodNumber>;
    hfcValue: z.ZodOptional<z.ZodNumber>;
    gwpReference: z.ZodDefault<z.ZodEnum<["AR4", "AR5", "AR6"]>>;
    source: z.ZodString;
    sourceUrl: z.ZodOptional<z.ZodString>;
    dataQualityTier: z.ZodDefault<z.ZodUnion<[z.ZodLiteral<1>, z.ZodLiteral<2>, z.ZodLiteral<3>, z.ZodLiteral<4>, z.ZodLiteral<5>]>>;
    uncertaintyPercentage: z.ZodDefault<z.ZodNumber>;
    externalAuditDate: z.ZodOptional<z.ZodString>;
    isProjection: z.ZodDefault<z.ZodBoolean>;
    decarbonizationTrend: z.ZodDefault<z.ZodNumber>;
    biologicalCarbonStorage: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["DRAFT", "ACTIVE", "DEPRECATED", "ARCHIVED"]>>;
    tags: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    value: number;
    status: "ACTIVE" | "ARCHIVED" | "DRAFT" | "DEPRECATED";
    name: string;
    tags: Record<string, string>;
    unit: "KWH" | "M3" | "L" | "KG" | "TON_KM" | "TJ" | "PASSENGER_KM";
    year: number;
    source: string;
    regionCode: string;
    activityType: "ELECTRICITY" | "DIESEL" | "LOGISTICS" | "NATURAL_GAS" | "FLIGHT" | "REFRIGERANT" | "WASTE";
    scope: 1 | 3 | 2;
    gwpReference: "AR4" | "AR5" | "AR6";
    dataQualityTier: 4 | 1 | 3 | 2 | 5;
    uncertaintyPercentage: number;
    isProjection: boolean;
    decarbonizationTrend: number;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    calculationMethod?: "LOCATION_BASED" | "MARKET_BASED" | undefined;
    co2Value?: number | undefined;
    ch4Value?: number | undefined;
    n2oValue?: number | undefined;
    hfcValue?: number | undefined;
    sourceUrl?: string | undefined;
    externalAuditDate?: string | undefined;
    biologicalCarbonStorage?: number | undefined;
}, {
    value: number;
    name: string;
    year: number;
    source: string;
    regionCode: string;
    status?: "ACTIVE" | "ARCHIVED" | "DRAFT" | "DEPRECATED" | undefined;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    unit?: unknown;
    calculationMethod?: unknown;
    activityType?: unknown;
    scope?: unknown;
    co2Value?: number | undefined;
    ch4Value?: number | undefined;
    n2oValue?: number | undefined;
    hfcValue?: number | undefined;
    gwpReference?: "AR4" | "AR5" | "AR6" | undefined;
    sourceUrl?: string | undefined;
    dataQualityTier?: 4 | 1 | 3 | 2 | 5 | undefined;
    uncertaintyPercentage?: number | undefined;
    externalAuditDate?: string | undefined;
    isProjection?: boolean | undefined;
    decarbonizationTrend?: number | undefined;
    biologicalCarbonStorage?: number | undefined;
}>;
export type EmissionFactorDTOInput = z.infer<typeof EmissionFactorDTOSchema>;
export declare class EmissionFactorDTO {
    readonly id: string;
    readonly name: string;
    readonly year: number;
    readonly regionCode: string;
    readonly activityType: z.infer<typeof EmissionFactorActivityTypeSchema>;
    readonly scope: z.infer<typeof EmissionFactorScopeNumberSchema>;
    readonly calculationMethod?: z.infer<typeof EmissionFactorCalculationMethodSchema>;
    readonly unit: z.infer<typeof EmissionFactorPhysicalUnitSchema>;
    readonly value: number;
    readonly co2Value?: number;
    readonly ch4Value?: number;
    readonly n2oValue?: number;
    readonly hfcValue?: number;
    readonly gwpReference: z.infer<typeof EmissionFactorGwpReferenceSchema>;
    readonly source: string;
    readonly sourceUrl?: string;
    readonly dataQualityTier: z.infer<typeof EmissionFactorDataQualityTierSchema>;
    readonly uncertaintyPercentage: number;
    readonly externalAuditDate?: string;
    readonly isProjection: boolean;
    readonly decarbonizationTrend: number;
    readonly biologicalCarbonStorage?: number;
    readonly status: z.infer<typeof EmissionFactorCatalogStatusSchema>;
    readonly tags: Record<string, string>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    constructor(id: string, name: string, year: number, regionCode: string, activityType: z.infer<typeof EmissionFactorActivityTypeSchema>, scope: z.infer<typeof EmissionFactorScopeNumberSchema>, calculationMethod: z.infer<typeof EmissionFactorCalculationMethodSchema> | null | undefined, unit: z.infer<typeof EmissionFactorPhysicalUnitSchema>, value: number, co2Value: number | null | undefined, ch4Value: number | null | undefined, n2oValue: number | null | undefined, hfcValue: number | null | undefined, gwpReference: z.infer<typeof EmissionFactorGwpReferenceSchema> | null | undefined, source: string, sourceUrl: string | null | undefined, dataQualityTier: z.infer<typeof EmissionFactorDataQualityTierSchema>, uncertaintyPercentage: number | null | undefined, externalAuditDate: string | null | undefined, isProjection: boolean | null | undefined, decarbonizationTrend: number | null | undefined, biologicalCarbonStorage: number | null | undefined, status: z.infer<typeof EmissionFactorCatalogStatusSchema>, tags: Record<string, string> | null | undefined, createdAt?: string, updatedAt?: string);
}
export declare const parseEmissionFactorDTO: (input: unknown) => EmissionFactorDTO;
export declare const safeParseEmissionFactorDTO: (input: unknown) => z.SafeParseReturnType<{
    value: number;
    name: string;
    year: number;
    source: string;
    regionCode: string;
    status?: "ACTIVE" | "ARCHIVED" | "DRAFT" | "DEPRECATED" | undefined;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    tags?: Record<string, string> | undefined;
    unit?: unknown;
    calculationMethod?: unknown;
    activityType?: unknown;
    scope?: unknown;
    co2Value?: number | undefined;
    ch4Value?: number | undefined;
    n2oValue?: number | undefined;
    hfcValue?: number | undefined;
    gwpReference?: "AR4" | "AR5" | "AR6" | undefined;
    sourceUrl?: string | undefined;
    dataQualityTier?: 4 | 1 | 3 | 2 | 5 | undefined;
    uncertaintyPercentage?: number | undefined;
    externalAuditDate?: string | undefined;
    isProjection?: boolean | undefined;
    decarbonizationTrend?: number | undefined;
    biologicalCarbonStorage?: number | undefined;
}, {
    value: number;
    status: "ACTIVE" | "ARCHIVED" | "DRAFT" | "DEPRECATED";
    name: string;
    tags: Record<string, string>;
    unit: "KWH" | "M3" | "L" | "KG" | "TON_KM" | "TJ" | "PASSENGER_KM";
    year: number;
    source: string;
    regionCode: string;
    activityType: "ELECTRICITY" | "DIESEL" | "LOGISTICS" | "NATURAL_GAS" | "FLIGHT" | "REFRIGERANT" | "WASTE";
    scope: 1 | 3 | 2;
    gwpReference: "AR4" | "AR5" | "AR6";
    dataQualityTier: 4 | 1 | 3 | 2 | 5;
    uncertaintyPercentage: number;
    isProjection: boolean;
    decarbonizationTrend: number;
    id?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    calculationMethod?: "LOCATION_BASED" | "MARKET_BASED" | undefined;
    co2Value?: number | undefined;
    ch4Value?: number | undefined;
    n2oValue?: number | undefined;
    hfcValue?: number | undefined;
    sourceUrl?: string | undefined;
    externalAuditDate?: string | undefined;
    biologicalCarbonStorage?: number | undefined;
}>;
//# sourceMappingURL=emission-factor.dto.d.ts.map