name: Terraform CI/CD

on:
  #workflow_dispatch: # <--- ESTO permite el botón "Run workflow" en GitHub Actions
  #Comentamos los automáticos para que no te sorprendan
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Actualizado a v4 (más rápido)

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 # Actualizado a v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Ajustala a tu región real si no es Virginia

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform Plan
        # Quitamos el -var-file si tu archivo se llama terraform.tfvars (lo toma solo)
        # Agregamos -input=false para que no se cuelgue 6 minutos si falta algo
        run: terraform plan -out=tfplan -input=false
        working-directory: ./terraform

      - name: Terraform Apply
        # Se ejecuta solo si le das al botón manual y estás en main
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform